//
// ShipmentAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ShipmentAPI {

    /**
     Create Shipment.
     
     - parameter merchantShipmentRequest: (body)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func shipmentCreate(merchantShipmentRequest: MerchantShipmentRequest? = nil, apiResponseQueue: DispatchQueue = ChannelEngineMerchantApiClientAPI.apiResponseQueue, completion: @escaping ((_ data: ApiResponse?, _ error: Error?) -> Void)) {
        shipmentCreateWithRequestBuilder(merchantShipmentRequest: merchantShipmentRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create Shipment.
     - POST /v2/shipments
     - Mark (part of) an order as shipped.
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apiKey
     - parameter merchantShipmentRequest: (body)  (optional)
     - returns: RequestBuilder<ApiResponse> 
     */
    open class func shipmentCreateWithRequestBuilder(merchantShipmentRequest: MerchantShipmentRequest? = nil) -> RequestBuilder<ApiResponse> {
        let localVariablePath = "/v2/shipments"
        let localVariableURLString = ChannelEngineMerchantApiClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: merchantShipmentRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Create shipment for channel provided shipping labels
     
     - parameter merchantChannelLabelShipmentRequest: (body) The shipment to create (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func shipmentCreateForChannelMethod(merchantChannelLabelShipmentRequest: MerchantChannelLabelShipmentRequest? = nil, apiResponseQueue: DispatchQueue = ChannelEngineMerchantApiClientAPI.apiResponseQueue, completion: @escaping ((_ data: ApiResponse?, _ error: Error?) -> Void)) {
        shipmentCreateForChannelMethodWithRequestBuilder(merchantChannelLabelShipmentRequest: merchantChannelLabelShipmentRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create shipment for channel provided shipping labels
     - POST /v2/shipments/channelmethod
     - Create a shipment, which will request a shipping label from the channel
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apiKey
     - parameter merchantChannelLabelShipmentRequest: (body) The shipment to create (optional)
     - returns: RequestBuilder<ApiResponse> 
     */
    open class func shipmentCreateForChannelMethodWithRequestBuilder(merchantChannelLabelShipmentRequest: MerchantChannelLabelShipmentRequest? = nil) -> RequestBuilder<ApiResponse> {
        let localVariablePath = "/v2/shipments/channelmethod"
        let localVariableURLString = ChannelEngineMerchantApiClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: merchantChannelLabelShipmentRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Get carriers for channel provided shipping labels
     
     - parameter merchantOrderNo: (path) The merchant&#39;s order reference. 
     - parameter merchantShipmentLabelCarrierRequest: (body) The parcel information (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func shipmentGetShipmentLabelCarriers(merchantOrderNo: String, merchantShipmentLabelCarrierRequest: MerchantShipmentLabelCarrierRequest? = nil, apiResponseQueue: DispatchQueue = ChannelEngineMerchantApiClientAPI.apiResponseQueue, completion: @escaping ((_ data: CollectionOfMerchantShipmentLabelCarrierResponse?, _ error: Error?) -> Void)) {
        shipmentGetShipmentLabelCarriersWithRequestBuilder(merchantOrderNo: merchantOrderNo, merchantShipmentLabelCarrierRequest: merchantShipmentLabelCarrierRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get carriers for channel provided shipping labels
     - POST /v2/carriers/{merchantOrderNo}
     - Get the carriers for buying a shipping label from the channel
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apiKey
     - parameter merchantOrderNo: (path) The merchant&#39;s order reference. 
     - parameter merchantShipmentLabelCarrierRequest: (body) The parcel information (optional)
     - returns: RequestBuilder<CollectionOfMerchantShipmentLabelCarrierResponse> 
     */
    open class func shipmentGetShipmentLabelCarriersWithRequestBuilder(merchantOrderNo: String, merchantShipmentLabelCarrierRequest: MerchantShipmentLabelCarrierRequest? = nil) -> RequestBuilder<CollectionOfMerchantShipmentLabelCarrierResponse> {
        var localVariablePath = "/v2/carriers/{merchantOrderNo}"
        let merchantOrderNoPreEscape = "\(APIHelper.mapValueToPathItem(merchantOrderNo))"
        let merchantOrderNoPostEscape = merchantOrderNoPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{merchantOrderNo}", with: merchantOrderNoPostEscape, options: .literal, range: nil)
        let localVariableURLString = ChannelEngineMerchantApiClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: merchantShipmentLabelCarrierRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CollectionOfMerchantShipmentLabelCarrierResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Get Shipments
     
     - parameter merchantShipmentNos: (query) Filter on the unique references (ids) as used by the merchant. (optional)
     - parameter merchantOrderNos: (query) Filter on the unique references (ids) of order as used by the merchant. (optional)
     - parameter method: (query) Filter on the shipping method. (optional)
     - parameter shippedFromCountryCodes: (query) 2-digit Country code (optional)
     - parameter fromShipmentDate: (query) Filter on the shipment date, starting from this date. This date is inclusive. (optional)
     - parameter toShipmentDate: (query) Filter on the shipment date, until this date. This date is exclusive. (optional)
     - parameter fromCreateDate: (query) Filter on the create date of the shipment in ChannelEngine, starting from this date. This date is inclusive. (optional)
     - parameter toCreateDate: (query) Filter on the create date of the shipment in ChannelEngine, until this date. This date is exclusive. (optional)
     - parameter fromUpdateDate: (query) Filter on the update date of the shipment in ChannelEngine, starting from this date. This date is inclusive. (optional)
     - parameter toUpdateDate: (query) Filter on the update date of the shipment in ChannelEngine, until this date. This date is exclusive. (optional)
     - parameter fulfillmentType: (query) Filter on the fulfillment type of the shipment. (optional)
     - parameter channelShipmentNos: (query) Filter on the unique references (ids) as used by the channel. (optional)
     - parameter channelOrderNos: (query) Filter on the unique references (ids) of order as used by the channel. (optional)
     - parameter page: (query) The page to filter on. Starts at 1. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func shipmentIndex(merchantShipmentNos: [String]? = nil, merchantOrderNos: [String]? = nil, method: String? = nil, shippedFromCountryCodes: [String]? = nil, fromShipmentDate: Date? = nil, toShipmentDate: Date? = nil, fromCreateDate: Date? = nil, toCreateDate: Date? = nil, fromUpdateDate: Date? = nil, toUpdateDate: Date? = nil, fulfillmentType: ShipmentFulfillmentType? = nil, channelShipmentNos: [String]? = nil, channelOrderNos: [String]? = nil, page: Int? = nil, apiResponseQueue: DispatchQueue = ChannelEngineMerchantApiClientAPI.apiResponseQueue, completion: @escaping ((_ data: CollectionOfMerchantShipmentResponse?, _ error: Error?) -> Void)) {
        shipmentIndexWithRequestBuilder(merchantShipmentNos: merchantShipmentNos, merchantOrderNos: merchantOrderNos, method: method, shippedFromCountryCodes: shippedFromCountryCodes, fromShipmentDate: fromShipmentDate, toShipmentDate: toShipmentDate, fromCreateDate: fromCreateDate, toCreateDate: toCreateDate, fromUpdateDate: fromUpdateDate, toUpdateDate: toUpdateDate, fulfillmentType: fulfillmentType, channelShipmentNos: channelShipmentNos, channelOrderNos: channelOrderNos, page: page).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get Shipments
     - GET /v2/shipments/merchant
     - Gets all shipments that meet conditions.<br />If all filters are empty return all in default order (from the oldest one).
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apiKey
     - parameter merchantShipmentNos: (query) Filter on the unique references (ids) as used by the merchant. (optional)
     - parameter merchantOrderNos: (query) Filter on the unique references (ids) of order as used by the merchant. (optional)
     - parameter method: (query) Filter on the shipping method. (optional)
     - parameter shippedFromCountryCodes: (query) 2-digit Country code (optional)
     - parameter fromShipmentDate: (query) Filter on the shipment date, starting from this date. This date is inclusive. (optional)
     - parameter toShipmentDate: (query) Filter on the shipment date, until this date. This date is exclusive. (optional)
     - parameter fromCreateDate: (query) Filter on the create date of the shipment in ChannelEngine, starting from this date. This date is inclusive. (optional)
     - parameter toCreateDate: (query) Filter on the create date of the shipment in ChannelEngine, until this date. This date is exclusive. (optional)
     - parameter fromUpdateDate: (query) Filter on the update date of the shipment in ChannelEngine, starting from this date. This date is inclusive. (optional)
     - parameter toUpdateDate: (query) Filter on the update date of the shipment in ChannelEngine, until this date. This date is exclusive. (optional)
     - parameter fulfillmentType: (query) Filter on the fulfillment type of the shipment. (optional)
     - parameter channelShipmentNos: (query) Filter on the unique references (ids) as used by the channel. (optional)
     - parameter channelOrderNos: (query) Filter on the unique references (ids) of order as used by the channel. (optional)
     - parameter page: (query) The page to filter on. Starts at 1. (optional)
     - returns: RequestBuilder<CollectionOfMerchantShipmentResponse> 
     */
    open class func shipmentIndexWithRequestBuilder(merchantShipmentNos: [String]? = nil, merchantOrderNos: [String]? = nil, method: String? = nil, shippedFromCountryCodes: [String]? = nil, fromShipmentDate: Date? = nil, toShipmentDate: Date? = nil, fromCreateDate: Date? = nil, toCreateDate: Date? = nil, fromUpdateDate: Date? = nil, toUpdateDate: Date? = nil, fulfillmentType: ShipmentFulfillmentType? = nil, channelShipmentNos: [String]? = nil, channelOrderNos: [String]? = nil, page: Int? = nil) -> RequestBuilder<CollectionOfMerchantShipmentResponse> {
        let localVariablePath = "/v2/shipments/merchant"
        let localVariableURLString = ChannelEngineMerchantApiClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "merchantShipmentNos": merchantShipmentNos?.encodeToJSON(),
            "merchantOrderNos": merchantOrderNos?.encodeToJSON(),
            "method": method?.encodeToJSON(),
            "shippedFromCountryCodes": shippedFromCountryCodes?.encodeToJSON(),
            "fromShipmentDate": fromShipmentDate?.encodeToJSON(),
            "toShipmentDate": toShipmentDate?.encodeToJSON(),
            "fromCreateDate": fromCreateDate?.encodeToJSON(),
            "toCreateDate": toCreateDate?.encodeToJSON(),
            "fromUpdateDate": fromUpdateDate?.encodeToJSON(),
            "toUpdateDate": toUpdateDate?.encodeToJSON(),
            "fulfillmentType": fulfillmentType?.encodeToJSON(),
            "channelShipmentNos": channelShipmentNos?.encodeToJSON(),
            "channelOrderNos": channelOrderNos?.encodeToJSON(),
            "page": page?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CollectionOfMerchantShipmentResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Download shipping label.
     
     - parameter merchantShipmentNo: (path) The unique shipment reference as used by the merchant. 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func shipmentShippingLabel(merchantShipmentNo: String, apiResponseQueue: DispatchQueue = ChannelEngineMerchantApiClientAPI.apiResponseQueue, completion: @escaping ((_ data: URL?, _ error: Error?) -> Void)) {
        shipmentShippingLabelWithRequestBuilder(merchantShipmentNo: merchantShipmentNo).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Download shipping label.
     - GET /v2/orders/{merchantShipmentNo}/shippinglabel
     - Downloads the shipping label for the shipment. There may pass some time between creating the shipment<br />and the availability of the label. So '404 Not Found' might incidate it is not available yet.
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apiKey
     - parameter merchantShipmentNo: (path) The unique shipment reference as used by the merchant. 
     - returns: RequestBuilder<URL> 
     */
    open class func shipmentShippingLabelWithRequestBuilder(merchantShipmentNo: String) -> RequestBuilder<URL> {
        var localVariablePath = "/v2/orders/{merchantShipmentNo}/shippinglabel"
        let merchantShipmentNoPreEscape = "\(APIHelper.mapValueToPathItem(merchantShipmentNo))"
        let merchantShipmentNoPostEscape = merchantShipmentNoPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{merchantShipmentNo}", with: merchantShipmentNoPostEscape, options: .literal, range: nil)
        let localVariableURLString = ChannelEngineMerchantApiClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }

    /**
     Update Shipment.
     
     - parameter merchantShipmentNo: (path) The merchant&#39;s shipment reference. 
     - parameter merchantShipmentTrackingRequest: (body) The updated tracking information. (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func shipmentUpdate(merchantShipmentNo: String, merchantShipmentTrackingRequest: MerchantShipmentTrackingRequest? = nil, apiResponseQueue: DispatchQueue = ChannelEngineMerchantApiClientAPI.apiResponseQueue, completion: @escaping ((_ data: ApiResponse?, _ error: Error?) -> Void)) {
        shipmentUpdateWithRequestBuilder(merchantShipmentNo: merchantShipmentNo, merchantShipmentTrackingRequest: merchantShipmentTrackingRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Update Shipment.
     - PUT /v2/shipments/{merchantShipmentNo}
     - Update an existing shipment with tracking information.
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apiKey
     - parameter merchantShipmentNo: (path) The merchant&#39;s shipment reference. 
     - parameter merchantShipmentTrackingRequest: (body) The updated tracking information. (optional)
     - returns: RequestBuilder<ApiResponse> 
     */
    open class func shipmentUpdateWithRequestBuilder(merchantShipmentNo: String, merchantShipmentTrackingRequest: MerchantShipmentTrackingRequest? = nil) -> RequestBuilder<ApiResponse> {
        var localVariablePath = "/v2/shipments/{merchantShipmentNo}"
        let merchantShipmentNoPreEscape = "\(APIHelper.mapValueToPathItem(merchantShipmentNo))"
        let merchantShipmentNoPostEscape = merchantShipmentNoPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{merchantShipmentNo}", with: merchantShipmentNoPostEscape, options: .literal, range: nil)
        let localVariableURLString = ChannelEngineMerchantApiClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: merchantShipmentTrackingRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
