name: ChannelEngineMerchantApiClient
targets:
  ChannelEngineMerchantApiClient:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [ChannelEngineMerchantApiClient]
    info:
      path: ./Info.plist
      version: 2.11.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
