//
// OrderAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class OrderAPI {
    /**
     Acknowledge Order
     
     - parameter model: (body) Relations between the id&#39;s returned by ChannelEngine and the references which the merchant uses 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func orderAcknowledge(model: MerchantOrderAcknowledgementRequest, completion: @escaping ((_ data: ApiResponse?,_ error: Error?) -> Void)) {
        orderAcknowledgeWithRequestBuilder(model: model).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Acknowledge Order
     - POST /v2/orders/acknowledge
     - Acknowledge an order. By acknowledging the order the merchant can confirm that  the order has been imported. When acknowledging an order the merchant has to supply  references that uniquely identify the order and the order lines. These references  will be used in the other API calls.
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apikey
     - examples: [{contentType=application/json, example={
  "Message" : "Message",
  "ValidationErrors" : {
    "key" : [ "ValidationErrors", "ValidationErrors" ]
  },
  "StatusCode" : 0,
  "LogId" : 6,
  "Success" : true
}}]
     
     - parameter model: (body) Relations between the id&#39;s returned by ChannelEngine and the references which the merchant uses 

     - returns: RequestBuilder<ApiResponse> 
     */
    open class func orderAcknowledgeWithRequestBuilder(model: MerchantOrderAcknowledgementRequest) -> RequestBuilder<ApiResponse> {
        let path = "/v2/orders/acknowledge"
        let URLString = ChannelEngineMerchantApiClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: model)

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
        ])

        let requestBuilder: RequestBuilder<ApiResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     * enum for parameter statuses
     */
    public enum Statuses_orderGetByFilter: String { 
        case inProgress = "IN_PROGRESS"
        case shipped = "SHIPPED"
        case inBackorder = "IN_BACKORDER"
        case manco = "MANCO"
        case inCombi = "IN_COMBI"
        case closed = "CLOSED"
        case new = "NEW"
        case returned = "RETURNED"
        case requiresCorrection = "REQUIRES_CORRECTION"
    }

    /**
     * enum for parameter fulfillmentType
     */
    public enum FulfillmentType_orderGetByFilter: String { 
        case all = "ALL"
        case onlyMerchant = "ONLY_MERCHANT"
        case onlyChannel = "ONLY_CHANNEL"
        case mixed = "MIXED"
    }

    /**
     Get Orders By Filter
     
     - parameter statuses: (query) Order status(es) to filter on (optional)
     - parameter emailAddresses: (query) Client emailaddresses to filter on (optional)
     - parameter merchantOrderNos: (query) Filter on unique order reference used by the merchant (optional)
     - parameter channelOrderNos: (query) Filter on unique order reference used by the channel (optional)
     - parameter fromDate: (query) Filter on the order date, starting from this date. This date is inclusive. (optional)
     - parameter toDate: (query) Filter on the order date, until this date. This date is exclusive. (optional)
     - parameter excludeMarketplaceFulfilledOrdersAndLines: (query) Exclude order (lines) fulfilled by the marketplace (amazon:FBA, bol:LVB, etc.) (optional)
     - parameter fulfillmentType: (query) Filter orders on fulfillment type. This will include all orders lines, even if they are partially fulfilled by the marketplace.  To exclude orders and lines that are fulfilled by the marketplace from the response, set ExcludeMarketplaceFulfilledOrdersAndLines to true. (optional)
     - parameter onlyWithCancellationRequests: (query) Filter on orders containing cancellation requests.  Some channels allow a customer to cancel an order until it has been shipped.  When an order has already been acknowledged in ChannelEngine, it can only be cancelled by creating a cancellation. (optional)
     - parameter page: (query) The page to filter on. Starts at 1. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func orderGetByFilter(statuses: [String]? = nil, emailAddresses: [String]? = nil, merchantOrderNos: [String]? = nil, channelOrderNos: [String]? = nil, fromDate: Date? = nil, toDate: Date? = nil, excludeMarketplaceFulfilledOrdersAndLines: Bool? = nil, fulfillmentType: FulfillmentType_orderGetByFilter? = nil, onlyWithCancellationRequests: Bool? = nil, page: Int? = nil, completion: @escaping ((_ data: CollectionOfMerchantOrderResponse?,_ error: Error?) -> Void)) {
        orderGetByFilterWithRequestBuilder(statuses: statuses, emailAddresses: emailAddresses, merchantOrderNos: merchantOrderNos, channelOrderNos: channelOrderNos, fromDate: fromDate, toDate: toDate, excludeMarketplaceFulfilledOrdersAndLines: excludeMarketplaceFulfilledOrdersAndLines, fulfillmentType: fulfillmentType, onlyWithCancellationRequests: onlyWithCancellationRequests, page: page).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get Orders By Filter
     - GET /v2/orders
     - Fetch orders based on the provided OrderFilter
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apikey
     - examples: [{contentType=application/json, example={
  "TotalCount" : 1,
  "Message" : "Message",
  "ValidationErrors" : {
    "key" : [ "ValidationErrors", "ValidationErrors" ]
  },
  "Content" : [ {
    "MerchantComment" : "MerchantComment",
    "Email" : "Email",
    "VatNo" : "VatNo",
    "SubTotalInclVat" : 5.962133916683182377482808078639209270477294921875,
    "CreatedAt" : "2000-01-23T04:56:07.000+00:00",
    "OriginalShippingCostsVat" : 7.3862819483858839220147274318151175975799560546875,
    "GlobalChannelId" : 1,
    "ChannelId" : 6,
    "BillingAddress" : {
      "StreetName" : "StreetName",
      "HouseNrAddition" : "HouseNrAddition",
      "CountryIso" : "CountryIso",
      "FirstName" : "FirstName",
      "ZipCode" : "ZipCode",
      "Gender" : "MALE",
      "City" : "City",
      "CompanyName" : "CompanyName",
      "HouseNr" : "HouseNr",
      "Region" : "Region",
      "LastName" : "LastName",
      "Line1" : "Line1",
      "Original" : "Original",
      "Line2" : "Line2",
      "Line3" : "Line3"
    },
    "OriginalSubTotalVat" : 2.027123023002321833274663731572218239307403564453125,
    "CurrencyCode" : "CurrencyCode",
    "CompanyRegistrationNo" : "CompanyRegistrationNo",
    "TotalVat" : 9.301444243932575517419536481611430644989013671875,
    "Phone" : "Phone",
    "ChannelCustomerNo" : "ChannelCustomerNo",
    "ChannelOrderSupport" : "NONE",
    "ShippingCostsVat" : 2.3021358869347654518833223846741020679473876953125,
    "SubTotalVat" : 5.63737665663332876420099637471139430999755859375,
    "TotalInclVat" : 7.061401241503109105224211816675961017608642578125,
    "Status" : "IN_PROGRESS",
    "ChannelOrderNo" : "ChannelOrderNo",
    "ExtraData" : {
      "key" : "ExtraData"
    },
    "UpdatedAt" : "2000-01-23T04:56:07.000+00:00",
    "GlobalChannelName" : "GlobalChannelName",
    "OrderDate" : "2000-01-23T04:56:07.000+00:00",
    "ChannelName" : "ChannelName",
    "ShippingAddress" : {
      "StreetName" : "StreetName",
      "HouseNrAddition" : "HouseNrAddition",
      "CountryIso" : "CountryIso",
      "FirstName" : "FirstName",
      "ZipCode" : "ZipCode",
      "Gender" : "MALE",
      "City" : "City",
      "CompanyName" : "CompanyName",
      "HouseNr" : "HouseNr",
      "Region" : "Region",
      "LastName" : "LastName",
      "Line1" : "Line1",
      "Original" : "Original",
      "Line2" : "Line2",
      "Line3" : "Line3"
    },
    "OriginalTotalVat" : 1.024645700144157789424070870154537260532379150390625,
    "ShippingCostsInclVat" : 3.557195227068097320710649000830017030239105224609375,
    "IsBusinessOrder" : true,
    "OriginalSubTotalInclVat" : 3.61607674925191080461672754609026014804840087890625,
    "PaymentMethod" : "PaymentMethod",
    "Id" : 0,
    "OriginalShippingCostsInclVat" : 4.1456080298839363962315474054776132106781005859375,
    "OriginalTotalInclVat" : 1.231513536777255612975068288506008684635162353515625,
    "Lines" : [ {
      "Status" : "IN_PROGRESS",
      "UnitPriceInclVat" : 8.7620420127490010742121739895083010196685791015625,
      "Condition" : "NEW",
      "UnitVat" : 1.489415909854170383397331534069962799549102783203125,
      "BundleProductMerchantProductNo" : "BundleProductMerchantProductNo",
      "FeeFixed" : 9.0183481860707832566959041287191212177276611328125,
      "FeeRate" : 6.438423552598546706349225132726132869720458984375,
      "Quantity" : 9,
      "OriginalUnitVat" : 4.9652184929849543237878606305457651615142822265625,
      "ExtraData" : [ {
        "Value" : "Value",
        "Key" : "Key"
      }, {
        "Value" : "Value",
        "Key" : "Key"
      } ],
      "IsFulfillmentByMarketplace" : true,
      "OriginalLineTotalInclVat" : 5.02500479152029466689555192715488374233245849609375,
      "Gtin" : "Gtin",
      "OriginalUnitPriceInclVat" : 1.173074250955943309548956676735542714595794677734375,
      "LineVat" : 7.4577447736837658709418974467553198337554931640625,
      "OriginalLineVat" : 9.965781217890562260208753286860883235931396484375,
      "CancellationRequestedQuantity" : 6,
      "MerchantProductNo" : "MerchantProductNo",
      "LineTotalInclVat" : 6.8468526983526398765889098285697400569915771484375,
      "ChannelProductNo" : "ChannelProductNo"
    }, {
      "Status" : "IN_PROGRESS",
      "UnitPriceInclVat" : 8.7620420127490010742121739895083010196685791015625,
      "Condition" : "NEW",
      "UnitVat" : 1.489415909854170383397331534069962799549102783203125,
      "BundleProductMerchantProductNo" : "BundleProductMerchantProductNo",
      "FeeFixed" : 9.0183481860707832566959041287191212177276611328125,
      "FeeRate" : 6.438423552598546706349225132726132869720458984375,
      "Quantity" : 9,
      "OriginalUnitVat" : 4.9652184929849543237878606305457651615142822265625,
      "ExtraData" : [ {
        "Value" : "Value",
        "Key" : "Key"
      }, {
        "Value" : "Value",
        "Key" : "Key"
      } ],
      "IsFulfillmentByMarketplace" : true,
      "OriginalLineTotalInclVat" : 5.02500479152029466689555192715488374233245849609375,
      "Gtin" : "Gtin",
      "OriginalUnitPriceInclVat" : 1.173074250955943309548956676735542714595794677734375,
      "LineVat" : 7.4577447736837658709418974467553198337554931640625,
      "OriginalLineVat" : 9.965781217890562260208753286860883235931396484375,
      "CancellationRequestedQuantity" : 6,
      "MerchantProductNo" : "MerchantProductNo",
      "LineTotalInclVat" : 6.8468526983526398765889098285697400569915771484375,
      "ChannelProductNo" : "ChannelProductNo"
    } ]
  }, {
    "MerchantComment" : "MerchantComment",
    "Email" : "Email",
    "VatNo" : "VatNo",
    "SubTotalInclVat" : 5.962133916683182377482808078639209270477294921875,
    "CreatedAt" : "2000-01-23T04:56:07.000+00:00",
    "OriginalShippingCostsVat" : 7.3862819483858839220147274318151175975799560546875,
    "GlobalChannelId" : 1,
    "ChannelId" : 6,
    "BillingAddress" : {
      "StreetName" : "StreetName",
      "HouseNrAddition" : "HouseNrAddition",
      "CountryIso" : "CountryIso",
      "FirstName" : "FirstName",
      "ZipCode" : "ZipCode",
      "Gender" : "MALE",
      "City" : "City",
      "CompanyName" : "CompanyName",
      "HouseNr" : "HouseNr",
      "Region" : "Region",
      "LastName" : "LastName",
      "Line1" : "Line1",
      "Original" : "Original",
      "Line2" : "Line2",
      "Line3" : "Line3"
    },
    "OriginalSubTotalVat" : 2.027123023002321833274663731572218239307403564453125,
    "CurrencyCode" : "CurrencyCode",
    "CompanyRegistrationNo" : "CompanyRegistrationNo",
    "TotalVat" : 9.301444243932575517419536481611430644989013671875,
    "Phone" : "Phone",
    "ChannelCustomerNo" : "ChannelCustomerNo",
    "ChannelOrderSupport" : "NONE",
    "ShippingCostsVat" : 2.3021358869347654518833223846741020679473876953125,
    "SubTotalVat" : 5.63737665663332876420099637471139430999755859375,
    "TotalInclVat" : 7.061401241503109105224211816675961017608642578125,
    "Status" : "IN_PROGRESS",
    "ChannelOrderNo" : "ChannelOrderNo",
    "ExtraData" : {
      "key" : "ExtraData"
    },
    "UpdatedAt" : "2000-01-23T04:56:07.000+00:00",
    "GlobalChannelName" : "GlobalChannelName",
    "OrderDate" : "2000-01-23T04:56:07.000+00:00",
    "ChannelName" : "ChannelName",
    "ShippingAddress" : {
      "StreetName" : "StreetName",
      "HouseNrAddition" : "HouseNrAddition",
      "CountryIso" : "CountryIso",
      "FirstName" : "FirstName",
      "ZipCode" : "ZipCode",
      "Gender" : "MALE",
      "City" : "City",
      "CompanyName" : "CompanyName",
      "HouseNr" : "HouseNr",
      "Region" : "Region",
      "LastName" : "LastName",
      "Line1" : "Line1",
      "Original" : "Original",
      "Line2" : "Line2",
      "Line3" : "Line3"
    },
    "OriginalTotalVat" : 1.024645700144157789424070870154537260532379150390625,
    "ShippingCostsInclVat" : 3.557195227068097320710649000830017030239105224609375,
    "IsBusinessOrder" : true,
    "OriginalSubTotalInclVat" : 3.61607674925191080461672754609026014804840087890625,
    "PaymentMethod" : "PaymentMethod",
    "Id" : 0,
    "OriginalShippingCostsInclVat" : 4.1456080298839363962315474054776132106781005859375,
    "OriginalTotalInclVat" : 1.231513536777255612975068288506008684635162353515625,
    "Lines" : [ {
      "Status" : "IN_PROGRESS",
      "UnitPriceInclVat" : 8.7620420127490010742121739895083010196685791015625,
      "Condition" : "NEW",
      "UnitVat" : 1.489415909854170383397331534069962799549102783203125,
      "BundleProductMerchantProductNo" : "BundleProductMerchantProductNo",
      "FeeFixed" : 9.0183481860707832566959041287191212177276611328125,
      "FeeRate" : 6.438423552598546706349225132726132869720458984375,
      "Quantity" : 9,
      "OriginalUnitVat" : 4.9652184929849543237878606305457651615142822265625,
      "ExtraData" : [ {
        "Value" : "Value",
        "Key" : "Key"
      }, {
        "Value" : "Value",
        "Key" : "Key"
      } ],
      "IsFulfillmentByMarketplace" : true,
      "OriginalLineTotalInclVat" : 5.02500479152029466689555192715488374233245849609375,
      "Gtin" : "Gtin",
      "OriginalUnitPriceInclVat" : 1.173074250955943309548956676735542714595794677734375,
      "LineVat" : 7.4577447736837658709418974467553198337554931640625,
      "OriginalLineVat" : 9.965781217890562260208753286860883235931396484375,
      "CancellationRequestedQuantity" : 6,
      "MerchantProductNo" : "MerchantProductNo",
      "LineTotalInclVat" : 6.8468526983526398765889098285697400569915771484375,
      "ChannelProductNo" : "ChannelProductNo"
    }, {
      "Status" : "IN_PROGRESS",
      "UnitPriceInclVat" : 8.7620420127490010742121739895083010196685791015625,
      "Condition" : "NEW",
      "UnitVat" : 1.489415909854170383397331534069962799549102783203125,
      "BundleProductMerchantProductNo" : "BundleProductMerchantProductNo",
      "FeeFixed" : 9.0183481860707832566959041287191212177276611328125,
      "FeeRate" : 6.438423552598546706349225132726132869720458984375,
      "Quantity" : 9,
      "OriginalUnitVat" : 4.9652184929849543237878606305457651615142822265625,
      "ExtraData" : [ {
        "Value" : "Value",
        "Key" : "Key"
      }, {
        "Value" : "Value",
        "Key" : "Key"
      } ],
      "IsFulfillmentByMarketplace" : true,
      "OriginalLineTotalInclVat" : 5.02500479152029466689555192715488374233245849609375,
      "Gtin" : "Gtin",
      "OriginalUnitPriceInclVat" : 1.173074250955943309548956676735542714595794677734375,
      "LineVat" : 7.4577447736837658709418974467553198337554931640625,
      "OriginalLineVat" : 9.965781217890562260208753286860883235931396484375,
      "CancellationRequestedQuantity" : 6,
      "MerchantProductNo" : "MerchantProductNo",
      "LineTotalInclVat" : 6.8468526983526398765889098285697400569915771484375,
      "ChannelProductNo" : "ChannelProductNo"
    } ]
  } ],
  "ItemsPerPage" : 2,
  "Count" : 6,
  "StatusCode" : 6,
  "LogId" : 6,
  "Success" : true
}}]
     
     - parameter statuses: (query) Order status(es) to filter on (optional)
     - parameter emailAddresses: (query) Client emailaddresses to filter on (optional)
     - parameter merchantOrderNos: (query) Filter on unique order reference used by the merchant (optional)
     - parameter channelOrderNos: (query) Filter on unique order reference used by the channel (optional)
     - parameter fromDate: (query) Filter on the order date, starting from this date. This date is inclusive. (optional)
     - parameter toDate: (query) Filter on the order date, until this date. This date is exclusive. (optional)
     - parameter excludeMarketplaceFulfilledOrdersAndLines: (query) Exclude order (lines) fulfilled by the marketplace (amazon:FBA, bol:LVB, etc.) (optional)
     - parameter fulfillmentType: (query) Filter orders on fulfillment type. This will include all orders lines, even if they are partially fulfilled by the marketplace.  To exclude orders and lines that are fulfilled by the marketplace from the response, set ExcludeMarketplaceFulfilledOrdersAndLines to true. (optional)
     - parameter onlyWithCancellationRequests: (query) Filter on orders containing cancellation requests.  Some channels allow a customer to cancel an order until it has been shipped.  When an order has already been acknowledged in ChannelEngine, it can only be cancelled by creating a cancellation. (optional)
     - parameter page: (query) The page to filter on. Starts at 1. (optional)

     - returns: RequestBuilder<CollectionOfMerchantOrderResponse> 
     */
    open class func orderGetByFilterWithRequestBuilder(statuses: [String]? = nil, emailAddresses: [String]? = nil, merchantOrderNos: [String]? = nil, channelOrderNos: [String]? = nil, fromDate: Date? = nil, toDate: Date? = nil, excludeMarketplaceFulfilledOrdersAndLines: Bool? = nil, fulfillmentType: FulfillmentType_orderGetByFilter? = nil, onlyWithCancellationRequests: Bool? = nil, page: Int? = nil) -> RequestBuilder<CollectionOfMerchantOrderResponse> {
        let path = "/v2/orders"
        let URLString = ChannelEngineMerchantApiClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "statuses": statuses, 
            "emailAddresses": emailAddresses, 
            "merchantOrderNos": merchantOrderNos, 
            "channelOrderNos": channelOrderNos, 
            "fromDate": fromDate?.encodeToJSON(), 
            "toDate": toDate?.encodeToJSON(), 
            "excludeMarketplaceFulfilledOrdersAndLines": excludeMarketplaceFulfilledOrdersAndLines, 
            "fulfillmentType": fulfillmentType?.rawValue, 
            "onlyWithCancellationRequests": onlyWithCancellationRequests, 
            "page": page?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<CollectionOfMerchantOrderResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get New Orders
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func orderGetNew(completion: @escaping ((_ data: CollectionOfMerchantOrderResponse?,_ error: Error?) -> Void)) {
        orderGetNewWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get New Orders
     - GET /v2/orders/new
     - Fetch newly placed orders (order with status NEW).
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apikey
     - examples: [{contentType=application/json, example={
  "TotalCount" : 1,
  "Message" : "Message",
  "ValidationErrors" : {
    "key" : [ "ValidationErrors", "ValidationErrors" ]
  },
  "Content" : [ {
    "MerchantComment" : "MerchantComment",
    "Email" : "Email",
    "VatNo" : "VatNo",
    "SubTotalInclVat" : 5.962133916683182377482808078639209270477294921875,
    "CreatedAt" : "2000-01-23T04:56:07.000+00:00",
    "OriginalShippingCostsVat" : 7.3862819483858839220147274318151175975799560546875,
    "GlobalChannelId" : 1,
    "ChannelId" : 6,
    "BillingAddress" : {
      "StreetName" : "StreetName",
      "HouseNrAddition" : "HouseNrAddition",
      "CountryIso" : "CountryIso",
      "FirstName" : "FirstName",
      "ZipCode" : "ZipCode",
      "Gender" : "MALE",
      "City" : "City",
      "CompanyName" : "CompanyName",
      "HouseNr" : "HouseNr",
      "Region" : "Region",
      "LastName" : "LastName",
      "Line1" : "Line1",
      "Original" : "Original",
      "Line2" : "Line2",
      "Line3" : "Line3"
    },
    "OriginalSubTotalVat" : 2.027123023002321833274663731572218239307403564453125,
    "CurrencyCode" : "CurrencyCode",
    "CompanyRegistrationNo" : "CompanyRegistrationNo",
    "TotalVat" : 9.301444243932575517419536481611430644989013671875,
    "Phone" : "Phone",
    "ChannelCustomerNo" : "ChannelCustomerNo",
    "ChannelOrderSupport" : "NONE",
    "ShippingCostsVat" : 2.3021358869347654518833223846741020679473876953125,
    "SubTotalVat" : 5.63737665663332876420099637471139430999755859375,
    "TotalInclVat" : 7.061401241503109105224211816675961017608642578125,
    "Status" : "IN_PROGRESS",
    "ChannelOrderNo" : "ChannelOrderNo",
    "ExtraData" : {
      "key" : "ExtraData"
    },
    "UpdatedAt" : "2000-01-23T04:56:07.000+00:00",
    "GlobalChannelName" : "GlobalChannelName",
    "OrderDate" : "2000-01-23T04:56:07.000+00:00",
    "ChannelName" : "ChannelName",
    "ShippingAddress" : {
      "StreetName" : "StreetName",
      "HouseNrAddition" : "HouseNrAddition",
      "CountryIso" : "CountryIso",
      "FirstName" : "FirstName",
      "ZipCode" : "ZipCode",
      "Gender" : "MALE",
      "City" : "City",
      "CompanyName" : "CompanyName",
      "HouseNr" : "HouseNr",
      "Region" : "Region",
      "LastName" : "LastName",
      "Line1" : "Line1",
      "Original" : "Original",
      "Line2" : "Line2",
      "Line3" : "Line3"
    },
    "OriginalTotalVat" : 1.024645700144157789424070870154537260532379150390625,
    "ShippingCostsInclVat" : 3.557195227068097320710649000830017030239105224609375,
    "IsBusinessOrder" : true,
    "OriginalSubTotalInclVat" : 3.61607674925191080461672754609026014804840087890625,
    "PaymentMethod" : "PaymentMethod",
    "Id" : 0,
    "OriginalShippingCostsInclVat" : 4.1456080298839363962315474054776132106781005859375,
    "OriginalTotalInclVat" : 1.231513536777255612975068288506008684635162353515625,
    "Lines" : [ {
      "Status" : "IN_PROGRESS",
      "UnitPriceInclVat" : 8.7620420127490010742121739895083010196685791015625,
      "Condition" : "NEW",
      "UnitVat" : 1.489415909854170383397331534069962799549102783203125,
      "BundleProductMerchantProductNo" : "BundleProductMerchantProductNo",
      "FeeFixed" : 9.0183481860707832566959041287191212177276611328125,
      "FeeRate" : 6.438423552598546706349225132726132869720458984375,
      "Quantity" : 9,
      "OriginalUnitVat" : 4.9652184929849543237878606305457651615142822265625,
      "ExtraData" : [ {
        "Value" : "Value",
        "Key" : "Key"
      }, {
        "Value" : "Value",
        "Key" : "Key"
      } ],
      "IsFulfillmentByMarketplace" : true,
      "OriginalLineTotalInclVat" : 5.02500479152029466689555192715488374233245849609375,
      "Gtin" : "Gtin",
      "OriginalUnitPriceInclVat" : 1.173074250955943309548956676735542714595794677734375,
      "LineVat" : 7.4577447736837658709418974467553198337554931640625,
      "OriginalLineVat" : 9.965781217890562260208753286860883235931396484375,
      "CancellationRequestedQuantity" : 6,
      "MerchantProductNo" : "MerchantProductNo",
      "LineTotalInclVat" : 6.8468526983526398765889098285697400569915771484375,
      "ChannelProductNo" : "ChannelProductNo"
    }, {
      "Status" : "IN_PROGRESS",
      "UnitPriceInclVat" : 8.7620420127490010742121739895083010196685791015625,
      "Condition" : "NEW",
      "UnitVat" : 1.489415909854170383397331534069962799549102783203125,
      "BundleProductMerchantProductNo" : "BundleProductMerchantProductNo",
      "FeeFixed" : 9.0183481860707832566959041287191212177276611328125,
      "FeeRate" : 6.438423552598546706349225132726132869720458984375,
      "Quantity" : 9,
      "OriginalUnitVat" : 4.9652184929849543237878606305457651615142822265625,
      "ExtraData" : [ {
        "Value" : "Value",
        "Key" : "Key"
      }, {
        "Value" : "Value",
        "Key" : "Key"
      } ],
      "IsFulfillmentByMarketplace" : true,
      "OriginalLineTotalInclVat" : 5.02500479152029466689555192715488374233245849609375,
      "Gtin" : "Gtin",
      "OriginalUnitPriceInclVat" : 1.173074250955943309548956676735542714595794677734375,
      "LineVat" : 7.4577447736837658709418974467553198337554931640625,
      "OriginalLineVat" : 9.965781217890562260208753286860883235931396484375,
      "CancellationRequestedQuantity" : 6,
      "MerchantProductNo" : "MerchantProductNo",
      "LineTotalInclVat" : 6.8468526983526398765889098285697400569915771484375,
      "ChannelProductNo" : "ChannelProductNo"
    } ]
  }, {
    "MerchantComment" : "MerchantComment",
    "Email" : "Email",
    "VatNo" : "VatNo",
    "SubTotalInclVat" : 5.962133916683182377482808078639209270477294921875,
    "CreatedAt" : "2000-01-23T04:56:07.000+00:00",
    "OriginalShippingCostsVat" : 7.3862819483858839220147274318151175975799560546875,
    "GlobalChannelId" : 1,
    "ChannelId" : 6,
    "BillingAddress" : {
      "StreetName" : "StreetName",
      "HouseNrAddition" : "HouseNrAddition",
      "CountryIso" : "CountryIso",
      "FirstName" : "FirstName",
      "ZipCode" : "ZipCode",
      "Gender" : "MALE",
      "City" : "City",
      "CompanyName" : "CompanyName",
      "HouseNr" : "HouseNr",
      "Region" : "Region",
      "LastName" : "LastName",
      "Line1" : "Line1",
      "Original" : "Original",
      "Line2" : "Line2",
      "Line3" : "Line3"
    },
    "OriginalSubTotalVat" : 2.027123023002321833274663731572218239307403564453125,
    "CurrencyCode" : "CurrencyCode",
    "CompanyRegistrationNo" : "CompanyRegistrationNo",
    "TotalVat" : 9.301444243932575517419536481611430644989013671875,
    "Phone" : "Phone",
    "ChannelCustomerNo" : "ChannelCustomerNo",
    "ChannelOrderSupport" : "NONE",
    "ShippingCostsVat" : 2.3021358869347654518833223846741020679473876953125,
    "SubTotalVat" : 5.63737665663332876420099637471139430999755859375,
    "TotalInclVat" : 7.061401241503109105224211816675961017608642578125,
    "Status" : "IN_PROGRESS",
    "ChannelOrderNo" : "ChannelOrderNo",
    "ExtraData" : {
      "key" : "ExtraData"
    },
    "UpdatedAt" : "2000-01-23T04:56:07.000+00:00",
    "GlobalChannelName" : "GlobalChannelName",
    "OrderDate" : "2000-01-23T04:56:07.000+00:00",
    "ChannelName" : "ChannelName",
    "ShippingAddress" : {
      "StreetName" : "StreetName",
      "HouseNrAddition" : "HouseNrAddition",
      "CountryIso" : "CountryIso",
      "FirstName" : "FirstName",
      "ZipCode" : "ZipCode",
      "Gender" : "MALE",
      "City" : "City",
      "CompanyName" : "CompanyName",
      "HouseNr" : "HouseNr",
      "Region" : "Region",
      "LastName" : "LastName",
      "Line1" : "Line1",
      "Original" : "Original",
      "Line2" : "Line2",
      "Line3" : "Line3"
    },
    "OriginalTotalVat" : 1.024645700144157789424070870154537260532379150390625,
    "ShippingCostsInclVat" : 3.557195227068097320710649000830017030239105224609375,
    "IsBusinessOrder" : true,
    "OriginalSubTotalInclVat" : 3.61607674925191080461672754609026014804840087890625,
    "PaymentMethod" : "PaymentMethod",
    "Id" : 0,
    "OriginalShippingCostsInclVat" : 4.1456080298839363962315474054776132106781005859375,
    "OriginalTotalInclVat" : 1.231513536777255612975068288506008684635162353515625,
    "Lines" : [ {
      "Status" : "IN_PROGRESS",
      "UnitPriceInclVat" : 8.7620420127490010742121739895083010196685791015625,
      "Condition" : "NEW",
      "UnitVat" : 1.489415909854170383397331534069962799549102783203125,
      "BundleProductMerchantProductNo" : "BundleProductMerchantProductNo",
      "FeeFixed" : 9.0183481860707832566959041287191212177276611328125,
      "FeeRate" : 6.438423552598546706349225132726132869720458984375,
      "Quantity" : 9,
      "OriginalUnitVat" : 4.9652184929849543237878606305457651615142822265625,
      "ExtraData" : [ {
        "Value" : "Value",
        "Key" : "Key"
      }, {
        "Value" : "Value",
        "Key" : "Key"
      } ],
      "IsFulfillmentByMarketplace" : true,
      "OriginalLineTotalInclVat" : 5.02500479152029466689555192715488374233245849609375,
      "Gtin" : "Gtin",
      "OriginalUnitPriceInclVat" : 1.173074250955943309548956676735542714595794677734375,
      "LineVat" : 7.4577447736837658709418974467553198337554931640625,
      "OriginalLineVat" : 9.965781217890562260208753286860883235931396484375,
      "CancellationRequestedQuantity" : 6,
      "MerchantProductNo" : "MerchantProductNo",
      "LineTotalInclVat" : 6.8468526983526398765889098285697400569915771484375,
      "ChannelProductNo" : "ChannelProductNo"
    }, {
      "Status" : "IN_PROGRESS",
      "UnitPriceInclVat" : 8.7620420127490010742121739895083010196685791015625,
      "Condition" : "NEW",
      "UnitVat" : 1.489415909854170383397331534069962799549102783203125,
      "BundleProductMerchantProductNo" : "BundleProductMerchantProductNo",
      "FeeFixed" : 9.0183481860707832566959041287191212177276611328125,
      "FeeRate" : 6.438423552598546706349225132726132869720458984375,
      "Quantity" : 9,
      "OriginalUnitVat" : 4.9652184929849543237878606305457651615142822265625,
      "ExtraData" : [ {
        "Value" : "Value",
        "Key" : "Key"
      }, {
        "Value" : "Value",
        "Key" : "Key"
      } ],
      "IsFulfillmentByMarketplace" : true,
      "OriginalLineTotalInclVat" : 5.02500479152029466689555192715488374233245849609375,
      "Gtin" : "Gtin",
      "OriginalUnitPriceInclVat" : 1.173074250955943309548956676735542714595794677734375,
      "LineVat" : 7.4577447736837658709418974467553198337554931640625,
      "OriginalLineVat" : 9.965781217890562260208753286860883235931396484375,
      "CancellationRequestedQuantity" : 6,
      "MerchantProductNo" : "MerchantProductNo",
      "LineTotalInclVat" : 6.8468526983526398765889098285697400569915771484375,
      "ChannelProductNo" : "ChannelProductNo"
    } ]
  } ],
  "ItemsPerPage" : 2,
  "Count" : 6,
  "StatusCode" : 6,
  "LogId" : 6,
  "Success" : true
}}]

     - returns: RequestBuilder<CollectionOfMerchantOrderResponse> 
     */
    open class func orderGetNewWithRequestBuilder() -> RequestBuilder<CollectionOfMerchantOrderResponse> {
        let path = "/v2/orders/new"
        let URLString = ChannelEngineMerchantApiClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
        ])

        let requestBuilder: RequestBuilder<CollectionOfMerchantOrderResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Download Invoice
     
     - parameter merchantOrderNo: (path) The unique order reference as used by the merchant 
     - parameter useCustomerCulture: (query) Generate the invoice in the billing address&#39; country&#39;s language (optional, default to false)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func orderInvoice(merchantOrderNo: String, useCustomerCulture: Bool? = nil, completion: @escaping ((_ data: URL?,_ error: Error?) -> Void)) {
        orderInvoiceWithRequestBuilder(merchantOrderNo: merchantOrderNo, useCustomerCulture: useCustomerCulture).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Download Invoice
     - GET /v2/orders/{merchantOrderNo}/invoice
     - Generates the ChannelEngine VAT invoice for this order in PDF
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apikey
     - examples: [{output=none}]
     
     - parameter merchantOrderNo: (path) The unique order reference as used by the merchant 
     - parameter useCustomerCulture: (query) Generate the invoice in the billing address&#39; country&#39;s language (optional, default to false)

     - returns: RequestBuilder<URL> 
     */
    open class func orderInvoiceWithRequestBuilder(merchantOrderNo: String, useCustomerCulture: Bool? = nil) -> RequestBuilder<URL> {
        var path = "/v2/orders/{merchantOrderNo}/invoice"
        let merchantOrderNoPreEscape = "\(merchantOrderNo)"
        let merchantOrderNoPostEscape = merchantOrderNoPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{merchantOrderNo}", with: merchantOrderNoPostEscape, options: .literal, range: nil)
        let URLString = ChannelEngineMerchantApiClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "useCustomerCulture": useCustomerCulture
        ])

        let requestBuilder: RequestBuilder<URL>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Download Packing Slip
     
     - parameter merchantOrderNo: (path) The unique order reference as used by the merchant 
     - parameter useCustomerCulture: (query) Generate the invoice in the billing address&#39; country&#39;s language (optional, default to false)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func orderPackingSlip(merchantOrderNo: String, useCustomerCulture: Bool? = nil, completion: @escaping ((_ data: URL?,_ error: Error?) -> Void)) {
        orderPackingSlipWithRequestBuilder(merchantOrderNo: merchantOrderNo, useCustomerCulture: useCustomerCulture).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Download Packing Slip
     - GET /v2/orders/{merchantOrderNo}/packingslip
     - Generates the ChannelEngine packing slip for this order in PDF
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apikey
     - examples: [{output=none}]
     
     - parameter merchantOrderNo: (path) The unique order reference as used by the merchant 
     - parameter useCustomerCulture: (query) Generate the invoice in the billing address&#39; country&#39;s language (optional, default to false)

     - returns: RequestBuilder<URL> 
     */
    open class func orderPackingSlipWithRequestBuilder(merchantOrderNo: String, useCustomerCulture: Bool? = nil) -> RequestBuilder<URL> {
        var path = "/v2/orders/{merchantOrderNo}/packingslip"
        let merchantOrderNoPreEscape = "\(merchantOrderNo)"
        let merchantOrderNoPostEscape = merchantOrderNoPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{merchantOrderNo}", with: merchantOrderNoPostEscape, options: .literal, range: nil)
        let URLString = ChannelEngineMerchantApiClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "useCustomerCulture": useCustomerCulture
        ])

        let requestBuilder: RequestBuilder<URL>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Update Comment
     
     - parameter model: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func orderUpdate(model: MerchantOrderCommentUpdateRequest, completion: @escaping ((_ data: ApiResponse?,_ error: Error?) -> Void)) {
        orderUpdateWithRequestBuilder(model: model).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update Comment
     - PUT /v2/orders/comment
     - Update the merchant comment for an order. Both the ChannelEngine order id as the   merchant order number can be used for updating a comment.
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apikey
     - examples: [{contentType=application/json, example={
  "Message" : "Message",
  "ValidationErrors" : {
    "key" : [ "ValidationErrors", "ValidationErrors" ]
  },
  "StatusCode" : 0,
  "LogId" : 6,
  "Success" : true
}}]
     
     - parameter model: (body)  

     - returns: RequestBuilder<ApiResponse> 
     */
    open class func orderUpdateWithRequestBuilder(model: MerchantOrderCommentUpdateRequest) -> RequestBuilder<ApiResponse> {
        let path = "/v2/orders/comment"
        let URLString = ChannelEngineMerchantApiClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: model)

        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
        ])

        let requestBuilder: RequestBuilder<ApiResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
