//
// ReturnAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class ReturnAPI {
    /**
     Create Return
     
     - parameter model: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func returnDeclareForMerchant(model: MerchantReturnRequest, completion: @escaping ((_ data: ApiResponse?,_ error: Error?) -> Void)) {
        returnDeclareForMerchantWithRequestBuilder(model: model).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Create Return
     - POST /v2/returns/merchant
     - Mark (part of) an order as returned by the customer.
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apikey
     - examples: [{contentType=application/json, example={
  "Message" : "Message",
  "ValidationErrors" : {
    "key" : [ "ValidationErrors", "ValidationErrors" ]
  },
  "StatusCode" : 0,
  "Success" : true
}}]
     
     - parameter model: (body)  

     - returns: RequestBuilder<ApiResponse> 
     */
    open class func returnDeclareForMerchantWithRequestBuilder(model: MerchantReturnRequest) -> RequestBuilder<ApiResponse> {
        let path = "/v2/returns/merchant"
        let URLString = ChannelEngineMerchantApiClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: model)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApiResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Get Returns
     
     - parameter createdSince: (query)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func returnGetDeclaredByChannel(createdSince: Date, completion: @escaping ((_ data: CollectionOfMerchantReturnResponse?,_ error: Error?) -> Void)) {
        returnGetDeclaredByChannelWithRequestBuilder(createdSince: createdSince).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get Returns
     - GET /v2/returns/merchant
     - Get all returns created by the channel. This call is supposed  to be used by merchants. Channels should use the 'GET /v2/returns/channel'  call.
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apikey
     - examples: [{contentType=application/json, example={
  "TotalCount" : 2,
  "Message" : "Message",
  "ValidationErrors" : {
    "key" : [ "ValidationErrors", "ValidationErrors" ]
  },
  "Content" : [ {
    "MerchantComment" : "MerchantComment",
    "RefundExclVat" : 5.962133916683182377482808078639209270477294921875,
    "CustomerComment" : "CustomerComment",
    "MerchantOrderNo" : "MerchantOrderNo",
    "Id" : 6,
    "Reason" : "PRODUCT_DEFECT",
    "Lines" : [ {
      "Quantity" : 0,
      "MerchantProductNo" : "MerchantProductNo"
    }, {
      "Quantity" : 0,
      "MerchantProductNo" : "MerchantProductNo"
    } ],
    "RefundInclVat" : 1.46581298050294517310021547018550336360931396484375
  }, {
    "MerchantComment" : "MerchantComment",
    "RefundExclVat" : 5.962133916683182377482808078639209270477294921875,
    "CustomerComment" : "CustomerComment",
    "MerchantOrderNo" : "MerchantOrderNo",
    "Id" : 6,
    "Reason" : "PRODUCT_DEFECT",
    "Lines" : [ {
      "Quantity" : 0,
      "MerchantProductNo" : "MerchantProductNo"
    }, {
      "Quantity" : 0,
      "MerchantProductNo" : "MerchantProductNo"
    } ],
    "RefundInclVat" : 1.46581298050294517310021547018550336360931396484375
  } ],
  "ItemsPerPage" : 7,
  "Count" : 5,
  "StatusCode" : 9,
  "Success" : true
}}]
     
     - parameter createdSince: (query)  

     - returns: RequestBuilder<CollectionOfMerchantReturnResponse> 
     */
    open class func returnGetDeclaredByChannelWithRequestBuilder(createdSince: Date) -> RequestBuilder<CollectionOfMerchantReturnResponse> {
        let path = "/v2/returns/merchant"
        let URLString = ChannelEngineMerchantApiClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "createdSince": createdSince.encodeToJSON()
        ])
        

        let requestBuilder: RequestBuilder<CollectionOfMerchantReturnResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Mark a return as received
     
     - parameter model: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func returnUpdateForMerchant(model: MerchantReturnUpdateRequest, completion: @escaping ((_ data: ApiResponse?,_ error: Error?) -> Void)) {
        returnUpdateForMerchantWithRequestBuilder(model: model).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Mark a return as received
     - PUT /v2/returns
     - Mark a return as received
     - API Key:
       - type: apiKey apikey (QUERY)
       - name: apikey
     - examples: [{contentType=application/json, example={
  "Message" : "Message",
  "ValidationErrors" : {
    "key" : [ "ValidationErrors", "ValidationErrors" ]
  },
  "StatusCode" : 0,
  "Success" : true
}}]
     
     - parameter model: (body)  

     - returns: RequestBuilder<ApiResponse> 
     */
    open class func returnUpdateForMerchantWithRequestBuilder(model: MerchantReturnUpdateRequest) -> RequestBuilder<ApiResponse> {
        let path = "/v2/returns"
        let URLString = ChannelEngineMerchantApiClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: model)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApiResponse>.Type = ChannelEngineMerchantApiClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
