//
// ChannelCarrierCollectionMethodApi.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ChannelCarrierCollectionMethodApi: String, Codable, CaseIterable {
    case dropOff = "DROP_OFF"
    case pickUp = "PICK_UP"
}
