//
// ChannelCarrierRecommendationApi.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ChannelCarrierRecommendationApi: String, Codable, CaseIterable {
    case neutral = "NEUTRAL"
    case recommended = "RECOMMENDED"
    case discommended = "DISCOMMENDED"
}
