//
// CreatorFilter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum CreatorFilter: String, Codable, CaseIterable {
    case onlyFromMerchant = "ONLY_FROM_MERCHANT"
    case onlyFromChannel = "ONLY_FROM_CHANNEL"
    case mixed = "MIXED"
}
