//
// ExtraDataType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum ExtraDataType: String, Codable, CaseIterable {
    case text = "TEXT"
    case number = "NUMBER"
    case url = "URL"
    case imageurl = "IMAGEURL"
}
