//
// ListedProductChannelStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ListedProductChannelStatus: String, Codable, CaseIterable {
    case _none = "NONE"
    case published = "PUBLISHED"
    case notPublished = "NOT_PUBLISHED"
    case unknown = "UNKNOWN"
    case underReview = "UNDER_REVIEW"
    case invalidOnCreate = "INVALID_ON_CREATE"
}
