//
// ListedProductExportStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ListedProductExportStatus: String, Codable, CaseIterable {
    case created = "CREATED"
    case updated = "UPDATED"
    case deleted = "DELETED"
    case createFailed = "CREATE_FAILED"
}
