//
// MerchantStockPriceUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct MerchantStockPriceUpdateRequest: Codable, Hashable {

    /** The unique product reference used by the Merchant (sku). */
    public var merchantProductNo: String
    /** The stock of the product. Should not be negative. */
    public var stock: Int?
    /** The price of the product. Should not be negative. */
    public var price: Double?

    public init(merchantProductNo: String, stock: Int? = nil, price: Double? = nil) {
        self.merchantProductNo = merchantProductNo
        self.stock = stock
        self.price = price
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchantProductNo = "MerchantProductNo"
        case stock = "Stock"
        case price = "Price"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(merchantProductNo, forKey: .merchantProductNo)
        try container.encodeIfPresent(stock, forKey: .stock)
        try container.encodeIfPresent(price, forKey: .price)
    }



}
