//
// MerchantStockLocationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantStockLocationResponse: Codable { 


    /** The ChannelEngine id of the stock location. */
    public var id: Int?
    /** The ChannelEngine name of the stock location. */
    public var name: String?

    public init(id: Int? = nil, name: String? = nil) {
        self.id = id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id = "Id"
        case name = "Name"
    }

}
