//
// MerchantShipmentPackageDimensionsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantShipmentPackageDimensionsRequest: Codable { 


    public var height: Double?
    public var width: Double?
    public var length: Double?
    public var unit: PackageDimensionsUnit?

    public init(height: Double? = nil, width: Double? = nil, length: Double? = nil, unit: PackageDimensionsUnit? = nil) {
        self.height = height
        self.width = width
        self.length = length
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case height = "Height"
        case width = "Width"
        case length = "Length"
        case unit = "Unit"
    }

}
