//
// MerchantOrderResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantOrderResponse: Codable { 


    /** The unique identifier used by ChannelEngine. This identifier does  not have to be saved. It should only be used in a call to acknowledge the order. */
    public var id: Int?
    /** The name of the channel for this specific environment/account. */
    public var channelName: String?
    /** The unique ID of the channel for this specific environment/account. */
    public var channelId: Int?
    /** The name of the channel across all of ChannelEngine. */
    public var globalChannelName: String?
    /** The unique ID of the channel across all of ChannelEngine. */
    public var globalChannelId: Int?
    public var channelOrderSupport: OrderSupport?
    /** The order reference used by the channel.  This number is not guaranteed to be unique accross all orders,  because different channels can use the same order number format. */
    public var channelOrderNo: String?
    public var status: OrderStatusView?
    /** Indicating whether the order is a business order. */
    public var isBusinessOrder: Bool?
    /** The date the order was created in ChannelEngine. */
    public var createdAt: Date?
    /** The date the order was last updated in ChannelEngine. */
    public var updatedAt: Date?
    /** The optional comment a merchant can add to an order. */
    public var merchantComment: String?
    public var billingAddress: MerchantAddressResponse?
    public var shippingAddress: MerchantAddressResponse?
    /** The total value of the order lines including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var subTotalInclVat: Double?
    /** The total amount of VAT charged over the order lines  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var subTotalVat: Double?
    /** The total amount of VAT charged over the shipping fee  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var shippingCostsVat: Double?
    /** The total value of the order including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var totalInclVat: Double?
    /** The total amount of VAT charged over the total value of te order  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var totalVat: Double?
    /** The total value of the order lines including VAT  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalSubTotalInclVat: Double?
    /** The total amount of VAT charged over the order lines  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalSubTotalVat: Double?
    /** The shipping fee including VAT  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalShippingCostsInclVat: Double?
    /** The total amount of VAT charged over the shipping fee  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalShippingCostsVat: Double?
    /** The total value of the order including VAT  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalTotalInclVat: Double?
    /** The total amount of VAT charged over the total value of te order  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalTotalVat: Double?
    public var lines: [MerchantOrderLineResponse]?
    /** The customer&#39;s telephone number. */
    public var phone: String?
    /** The customer&#39;s email. */
    public var email: String
    /** Optional. A company&#39;s chamber of commerce number. */
    public var companyRegistrationNo: String?
    /** Optional. A company&#39;s VAT number. */
    public var vatNo: String?
    /** The payment method used on the order. */
    public var paymentMethod: String?
    /** The shipping fee including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var shippingCostsInclVat: Double
    /** The currency code for the amounts of the order. */
    public var currencyCode: String
    /** The date the order was created at the channel. */
    public var orderDate: Date
    /** The unique customer reference used by the channel. */
    public var channelCustomerNo: String?
    /** Extra data on the order. */
    public var extraData: [String:String]?

    public init(id: Int? = nil, channelName: String? = nil, channelId: Int? = nil, globalChannelName: String? = nil, globalChannelId: Int? = nil, channelOrderSupport: OrderSupport? = nil, channelOrderNo: String? = nil, status: OrderStatusView? = nil, isBusinessOrder: Bool? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, merchantComment: String? = nil, billingAddress: MerchantAddressResponse? = nil, shippingAddress: MerchantAddressResponse? = nil, subTotalInclVat: Double? = nil, subTotalVat: Double? = nil, shippingCostsVat: Double? = nil, totalInclVat: Double? = nil, totalVat: Double? = nil, originalSubTotalInclVat: Double? = nil, originalSubTotalVat: Double? = nil, originalShippingCostsInclVat: Double? = nil, originalShippingCostsVat: Double? = nil, originalTotalInclVat: Double? = nil, originalTotalVat: Double? = nil, lines: [MerchantOrderLineResponse]? = nil, phone: String? = nil, email: String, companyRegistrationNo: String? = nil, vatNo: String? = nil, paymentMethod: String? = nil, shippingCostsInclVat: Double, currencyCode: String, orderDate: Date, channelCustomerNo: String? = nil, extraData: [String:String]? = nil) {
        self.id = id
        self.channelName = channelName
        self.channelId = channelId
        self.globalChannelName = globalChannelName
        self.globalChannelId = globalChannelId
        self.channelOrderSupport = channelOrderSupport
        self.channelOrderNo = channelOrderNo
        self.status = status
        self.isBusinessOrder = isBusinessOrder
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.merchantComment = merchantComment
        self.billingAddress = billingAddress
        self.shippingAddress = shippingAddress
        self.subTotalInclVat = subTotalInclVat
        self.subTotalVat = subTotalVat
        self.shippingCostsVat = shippingCostsVat
        self.totalInclVat = totalInclVat
        self.totalVat = totalVat
        self.originalSubTotalInclVat = originalSubTotalInclVat
        self.originalSubTotalVat = originalSubTotalVat
        self.originalShippingCostsInclVat = originalShippingCostsInclVat
        self.originalShippingCostsVat = originalShippingCostsVat
        self.originalTotalInclVat = originalTotalInclVat
        self.originalTotalVat = originalTotalVat
        self.lines = lines
        self.phone = phone
        self.email = email
        self.companyRegistrationNo = companyRegistrationNo
        self.vatNo = vatNo
        self.paymentMethod = paymentMethod
        self.shippingCostsInclVat = shippingCostsInclVat
        self.currencyCode = currencyCode
        self.orderDate = orderDate
        self.channelCustomerNo = channelCustomerNo
        self.extraData = extraData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id = "Id"
        case channelName = "ChannelName"
        case channelId = "ChannelId"
        case globalChannelName = "GlobalChannelName"
        case globalChannelId = "GlobalChannelId"
        case channelOrderSupport = "ChannelOrderSupport"
        case channelOrderNo = "ChannelOrderNo"
        case status = "Status"
        case isBusinessOrder = "IsBusinessOrder"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case merchantComment = "MerchantComment"
        case billingAddress = "BillingAddress"
        case shippingAddress = "ShippingAddress"
        case subTotalInclVat = "SubTotalInclVat"
        case subTotalVat = "SubTotalVat"
        case shippingCostsVat = "ShippingCostsVat"
        case totalInclVat = "TotalInclVat"
        case totalVat = "TotalVat"
        case originalSubTotalInclVat = "OriginalSubTotalInclVat"
        case originalSubTotalVat = "OriginalSubTotalVat"
        case originalShippingCostsInclVat = "OriginalShippingCostsInclVat"
        case originalShippingCostsVat = "OriginalShippingCostsVat"
        case originalTotalInclVat = "OriginalTotalInclVat"
        case originalTotalVat = "OriginalTotalVat"
        case lines = "Lines"
        case phone = "Phone"
        case email = "Email"
        case companyRegistrationNo = "CompanyRegistrationNo"
        case vatNo = "VatNo"
        case paymentMethod = "PaymentMethod"
        case shippingCostsInclVat = "ShippingCostsInclVat"
        case currencyCode = "CurrencyCode"
        case orderDate = "OrderDate"
        case channelCustomerNo = "ChannelCustomerNo"
        case extraData = "ExtraData"
    }

}
