//
// MerchantShipmentPackageWeightRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantShipmentPackageWeightRequest: Codable { 


    public var value: Double?
    public var unit: PackageWeightUnit?

    public init(value: Double? = nil, unit: PackageWeightUnit? = nil) {
        self.value = value
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case value = "Value"
        case unit = "Unit"
    }

}
