//
// MerchantOrderCommentUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct MerchantOrderCommentUpdateRequest: Codable, Hashable {

    /** Your own order reference for the order you would like to update the comment for.  Either this field or OrderId is required */
    public var merchantOrderNo: String?
    /** The ChannelEngine order ID of the order you would like to update the comment for.  Either this field or MerchantOrderNo is required */
    public var orderId: Int?
    /** The merchant comment you would like add / update for the order. */
    public var merchantComment: String

    public init(merchantOrderNo: String? = nil, orderId: Int? = nil, merchantComment: String) {
        self.merchantOrderNo = merchantOrderNo
        self.orderId = orderId
        self.merchantComment = merchantComment
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchantOrderNo = "MerchantOrderNo"
        case orderId = "OrderId"
        case merchantComment = "MerchantComment"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(merchantOrderNo, forKey: .merchantOrderNo)
        try container.encodeIfPresent(orderId, forKey: .orderId)
        try container.encode(merchantComment, forKey: .merchantComment)
    }



}
