//
// MerchantCancellationLineRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantCancellationLineRequest: Codable { 


    /** The unique product reference used by the Merchant (sku). */
    public var merchantProductNo: String
    /** Quantity of the product to cancel. */
    public var quantity: Int

    public init(merchantProductNo: String, quantity: Int) {
        self.merchantProductNo = merchantProductNo
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case merchantProductNo = "MerchantProductNo"
        case quantity = "Quantity"
    }

}
