//
// MerchantReturnAcknowledgeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MerchantReturnAcknowledgeRequest: Codable, Hashable {

    public var returnId: Int?
    public var merchantReturnNo: String

    public init(returnId: Int? = nil, merchantReturnNo: String) {
        self.returnId = returnId
        self.merchantReturnNo = merchantReturnNo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case returnId = "ReturnId"
        case merchantReturnNo = "MerchantReturnNo"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(returnId, forKey: .returnId)
        try container.encode(merchantReturnNo, forKey: .merchantReturnNo)
    }
}

