//
// MerchantShipmentLabelCarrierRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantShipmentLabelCarrierRequest: Codable { 


    public var lines: [MerchantShipmentLineRequest]
    public var dimensions: MerchantShipmentPackageDimensionsRequest
    public var weight: MerchantShipmentPackageWeightRequest

    public init(lines: [MerchantShipmentLineRequest], dimensions: MerchantShipmentPackageDimensionsRequest, weight: MerchantShipmentPackageWeightRequest) {
        self.lines = lines
        self.dimensions = dimensions
        self.weight = weight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case lines = "Lines"
        case dimensions = "Dimensions"
        case weight = "Weight"
    }

}
