//
// MerchantProductBundlePartResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantProductBundlePartResponse: Codable { 


    public var merchantProductNo: String?
    public var ean: String?
    public var name: String?
    public var quantity: Int?
    public var price: Double?

    public init(merchantProductNo: String? = nil, ean: String? = nil, name: String? = nil, quantity: Int? = nil, price: Double? = nil) {
        self.merchantProductNo = merchantProductNo
        self.ean = ean
        self.name = name
        self.quantity = quantity
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case merchantProductNo = "MerchantProductNo"
        case ean = "Ean"
        case name = "Name"
        case quantity = "Quantity"
        case price = "Price"
    }

}
