//
// MerchantReturnRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantReturnRequest: Codable { 


    /** The unique order reference used by the Merchant (sku). */
    public var merchantOrderNo: String
    /** The unique return reference used by the Merchant (sku). */
    public var merchantReturnNo: String
    public var lines: [MerchantReturnLineRequest]
    /** The unique return reference used by ChannelEngine. */
    public var id: Int?
    public var reason: ReturnReason?
    /** Optional. Comment of customer on the (reason of) the return. */
    public var customerComment: String?
    /** Optional. Comment of merchant on the return. */
    public var merchantComment: String?
    /** Refund amount incl. VAT. */
    public var refundInclVat: Double?
    /** Refund amount excl. VAT. */
    public var refundExclVat: Double?

    public init(merchantOrderNo: String, merchantReturnNo: String, lines: [MerchantReturnLineRequest], id: Int? = nil, reason: ReturnReason? = nil, customerComment: String? = nil, merchantComment: String? = nil, refundInclVat: Double? = nil, refundExclVat: Double? = nil) {
        self.merchantOrderNo = merchantOrderNo
        self.merchantReturnNo = merchantReturnNo
        self.lines = lines
        self.id = id
        self.reason = reason
        self.customerComment = customerComment
        self.merchantComment = merchantComment
        self.refundInclVat = refundInclVat
        self.refundExclVat = refundExclVat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case merchantOrderNo = "MerchantOrderNo"
        case merchantReturnNo = "MerchantReturnNo"
        case lines = "Lines"
        case id = "Id"
        case reason = "Reason"
        case customerComment = "CustomerComment"
        case merchantComment = "MerchantComment"
        case refundInclVat = "RefundInclVat"
        case refundExclVat = "RefundExclVat"
    }

}
