//
// MerchantCancellationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct MerchantCancellationRequest: Codable, Hashable {

    /** The unique cancellation reference used by the Merchant (sku). */
    public var merchantCancellationNo: String
    /** The unique order reference used by the Merchant (sku). */
    public var merchantOrderNo: String
    public var lines: [MerchantCancellationLineRequest]
    /** Reason for cancellation (text). */
    public var reason: String?
    public var reasonCode: MancoReason?

    public init(merchantCancellationNo: String, merchantOrderNo: String, lines: [MerchantCancellationLineRequest], reason: String? = nil, reasonCode: MancoReason? = nil) {
        self.merchantCancellationNo = merchantCancellationNo
        self.merchantOrderNo = merchantOrderNo
        self.lines = lines
        self.reason = reason
        self.reasonCode = reasonCode
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchantCancellationNo = "MerchantCancellationNo"
        case merchantOrderNo = "MerchantOrderNo"
        case lines = "Lines"
        case reason = "Reason"
        case reasonCode = "ReasonCode"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(merchantCancellationNo, forKey: .merchantCancellationNo)
        try container.encode(merchantOrderNo, forKey: .merchantOrderNo)
        try container.encode(lines, forKey: .lines)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(reasonCode, forKey: .reasonCode)
    }



}
