//
// MerchantCancellationLineRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct MerchantCancellationLineRequest: Codable, Hashable {

    /** The unique product reference used by the Merchant (sku). */
    public var merchantProductNo: String
    /** Quantity of the product to cancel. */
    public var quantity: Int

    public init(merchantProductNo: String, quantity: Int) {
        self.merchantProductNo = merchantProductNo
        self.quantity = quantity
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchantProductNo = "MerchantProductNo"
        case quantity = "Quantity"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(merchantProductNo, forKey: .merchantProductNo)
        try container.encode(quantity, forKey: .quantity)
    }



}
