//
// MerchantChannelLabelShipmentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantChannelLabelShipmentRequest: Codable { 


    public var dimensions: MerchantShipmentPackageDimensionsRequest
    public var weight: MerchantShipmentPackageWeightRequest
    public var channelMethodCode: String
    /** The unique shipment reference used by the Merchant. */
    public var merchantShipmentNo: String
    /** The unique order reference used by the Merchant. */
    public var merchantOrderNo: String
    public var lines: [MerchantShipmentLineRequest]

    public init(dimensions: MerchantShipmentPackageDimensionsRequest, weight: MerchantShipmentPackageWeightRequest, channelMethodCode: String, merchantShipmentNo: String, merchantOrderNo: String, lines: [MerchantShipmentLineRequest]) {
        self.dimensions = dimensions
        self.weight = weight
        self.channelMethodCode = channelMethodCode
        self.merchantShipmentNo = merchantShipmentNo
        self.merchantOrderNo = merchantOrderNo
        self.lines = lines
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case dimensions = "Dimensions"
        case weight = "Weight"
        case channelMethodCode = "ChannelMethodCode"
        case merchantShipmentNo = "MerchantShipmentNo"
        case merchantOrderNo = "MerchantOrderNo"
        case lines = "Lines"
    }

}
