//
// MerchantReturnUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantReturnUpdateRequest: Codable { 


    /** The ChannelEngine return ID of the return you would like to update. */
    public var returnId: Int
    public var lines: [MerchantReturnLineUpdateRequest]

    public init(returnId: Int, lines: [MerchantReturnLineUpdateRequest]) {
        self.returnId = returnId
        self.lines = lines
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case returnId = "ReturnId"
        case lines = "Lines"
    }

}
