//
// MerchantReturnLineResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantReturnLineResponse: Codable { 


    /** The unique product reference used by the Merchant (sku). */
    public var merchantProductNo: String?
    /** Number of items of the product in this return. */
    public var quantity: Int

    public init(merchantProductNo: String? = nil, quantity: Int) {
        self.merchantProductNo = merchantProductNo
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case merchantProductNo = "MerchantProductNo"
        case quantity = "Quantity"
    }

}
