//
// MerchantReturnResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantReturnResponse: Codable { 


    /** The unique order reference used by the Merchant. */
    public var merchantOrderNo: String?
    /** The unique order reference used by the Channel. */
    public var channelOrderNo: String?
    public var lines: [MerchantReturnLineResponse]?
    /** The date at which the return was created in ChannelEngine. */
    public var createdAt: Date?
    /** The date at which the return was last modified in ChannelEngine. */
    public var updatedAt: Date?
    /** The unique return reference used by the Merchant, will be empty in case of a channel or unacknowledged return. */
    public var merchantReturnNo: String?
    /** The unique return reference used by the Channel, will be empty in case of a merchant return. */
    public var channelReturnNo: String?
    /** The unique return reference used by ChannelEngine. */
    public var id: Int?
    public var reason: ReturnReason?
    /** Optional. Comment of customer on the (reason of) the return. */
    public var customerComment: String?
    /** Optional. Comment of merchant on the return. */
    public var merchantComment: String?
    /** Refund amount incl. VAT. */
    public var refundInclVat: Double?
    /** Refund amount excl. VAT. */
    public var refundExclVat: Double?

    public init(merchantOrderNo: String? = nil, channelOrderNo: String? = nil, lines: [MerchantReturnLineResponse]? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, merchantReturnNo: String? = nil, channelReturnNo: String? = nil, id: Int? = nil, reason: ReturnReason? = nil, customerComment: String? = nil, merchantComment: String? = nil, refundInclVat: Double? = nil, refundExclVat: Double? = nil) {
        self.merchantOrderNo = merchantOrderNo
        self.channelOrderNo = channelOrderNo
        self.lines = lines
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.merchantReturnNo = merchantReturnNo
        self.channelReturnNo = channelReturnNo
        self.id = id
        self.reason = reason
        self.customerComment = customerComment
        self.merchantComment = merchantComment
        self.refundInclVat = refundInclVat
        self.refundExclVat = refundExclVat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case merchantOrderNo = "MerchantOrderNo"
        case channelOrderNo = "ChannelOrderNo"
        case lines = "Lines"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case merchantReturnNo = "MerchantReturnNo"
        case channelReturnNo = "ChannelReturnNo"
        case id = "Id"
        case reason = "Reason"
        case customerComment = "CustomerComment"
        case merchantComment = "MerchantComment"
        case refundInclVat = "RefundInclVat"
        case refundExclVat = "RefundExclVat"
    }

}
