//
// MerchantReturnLineRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MerchantReturnLineRequest: Codable, Hashable {

    /** The unique product reference used by the Merchant (sku). */
    public var merchantProductNo: String
    /** Number of items of the product in this return. */
    public var quantity: Int
    /** Extra data on the returnline. Each item must have an unqiue key */
    public var extraData: [String: String]?

    public init(merchantProductNo: String, quantity: Int, extraData: [String: String]? = nil) {
        self.merchantProductNo = merchantProductNo
        self.quantity = quantity
        self.extraData = extraData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchantProductNo = "MerchantProductNo"
        case quantity = "Quantity"
        case extraData = "ExtraData"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(merchantProductNo, forKey: .merchantProductNo)
        try container.encode(quantity, forKey: .quantity)
        try container.encodeIfPresent(extraData, forKey: .extraData)
    }
}

