//
// MerchantShipmentLineResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MerchantShipmentLineResponse: Codable, Hashable {

    /** The unique product reference used by the Merchant. */
    public var merchantProductNo: String
    /** The unique product reference used by the Channel. */
    public var channelProductNo: String?
    public var orderLine: MerchantOrderLineResponse?
    public var shipmentStatus: ShipmentLineStatus?
    /** Extra data on the shipment line. Each item must have an unqiue key */
    public var extraData: [String: String]?
    /** Number of items of the product in the shipment. */
    public var quantity: Int

    public init(merchantProductNo: String, channelProductNo: String? = nil, orderLine: MerchantOrderLineResponse? = nil, shipmentStatus: ShipmentLineStatus? = nil, extraData: [String: String]? = nil, quantity: Int) {
        self.merchantProductNo = merchantProductNo
        self.channelProductNo = channelProductNo
        self.orderLine = orderLine
        self.shipmentStatus = shipmentStatus
        self.extraData = extraData
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case merchantProductNo = "MerchantProductNo"
        case channelProductNo = "ChannelProductNo"
        case orderLine = "OrderLine"
        case shipmentStatus = "ShipmentStatus"
        case extraData = "ExtraData"
        case quantity = "Quantity"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(merchantProductNo, forKey: .merchantProductNo)
        try container.encodeIfPresent(channelProductNo, forKey: .channelProductNo)
        try container.encodeIfPresent(orderLine, forKey: .orderLine)
        try container.encodeIfPresent(shipmentStatus, forKey: .shipmentStatus)
        try container.encodeIfPresent(extraData, forKey: .extraData)
        try container.encode(quantity, forKey: .quantity)
    }
}

