//
// MerchantProductBundleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MerchantProductBundleResponse: Codable { 


    public var merchantProductNo: String?
    public var ean: String?
    public var name: String?
    public var price: Double?
    public var parts: [MerchantProductBundlePartResponse]?

    public init(merchantProductNo: String? = nil, ean: String? = nil, name: String? = nil, price: Double? = nil, parts: [MerchantProductBundlePartResponse]? = nil) {
        self.merchantProductNo = merchantProductNo
        self.ean = ean
        self.name = name
        self.price = price
        self.parts = parts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case merchantProductNo = "MerchantProductNo"
        case ean = "Ean"
        case name = "Name"
        case price = "Price"
        case parts = "Parts"
    }

}
