//
// PackageWeightUnit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum PackageWeightUnit: String, Codable, CaseIterable {
    case gram = "GRAM"
    case ounce = "OUNCE"
}
