//
// ProductMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ProductMessage: Codable, Hashable {

    public var name: String?
    public var reference: String?
    public var warnings: [String]?
    public var errors: [String]?

    public init(name: String? = nil, reference: String? = nil, warnings: [String]? = nil, errors: [String]? = nil) {
        self.name = name
        self.reference = reference
        self.warnings = warnings
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case reference = "Reference"
        case warnings = "Warnings"
        case errors = "Errors"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(reference, forKey: .reference)
        try container.encodeIfPresent(warnings, forKey: .warnings)
        try container.encodeIfPresent(errors, forKey: .errors)
    }
}

