//
// ProductCreationResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ProductCreationResult: Codable { 


    public var rejectedCount: Int?
    public var acceptedCount: Int?
    /** Messages about the rejected products. */
    public var productMessages: [ProductMessage]?

    public init(rejectedCount: Int? = nil, acceptedCount: Int? = nil, productMessages: [ProductMessage]? = nil) {
        self.rejectedCount = rejectedCount
        self.acceptedCount = acceptedCount
        self.productMessages = productMessages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case rejectedCount = "RejectedCount"
        case acceptedCount = "AcceptedCount"
        case productMessages = "ProductMessages"
    }

}
