//
// ProductMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ProductMessage: Codable { 


    public var name: String?
    public var reference: String?
    public var warnings: [String]?
    public var errors: [String]?

    public init(name: String? = nil, reference: String? = nil, warnings: [String]? = nil, errors: [String]? = nil) {
        self.name = name
        self.reference = reference
        self.warnings = warnings
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name = "Name"
        case reference = "Reference"
        case warnings = "Warnings"
        case errors = "Errors"
    }

}
