//
// ShipmentLineStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum ShipmentLineStatus: String, Codable, CaseIterable {
    case shipped = "SHIPPED"
    case inBackorder = "IN_BACKORDER"
    case manco = "MANCO"
}
