//
// VatRateType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum VatRateType: String, Codable, CaseIterable {
    case standard = "STANDARD"
    case reduced = "REDUCED"
    case superReduced = "SUPER_REDUCED"
    case exempt = "EXEMPT"
}
