//
// WebhookEventType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public enum WebhookEventType: String, Codable, CaseIterable {
    case ordersChange = "ORDERS_CHANGE"
    case productsChange = "PRODUCTS_CHANGE"
    case returnsChange = "RETURNS_CHANGE"
    case shipmentsChange = "SHIPMENTS_CHANGE"
    case notificationsChange = "NOTIFICATIONS_CHANGE"
    case bundleProductsChange = "BUNDLE_PRODUCTS_CHANGE"
}
