//
// ExtraDataItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExtraDataItem: Codable {

    public enum ModelType: String, Codable { 
        case text = "TEXT"
        case number = "NUMBER"
        case url = "URL"
        case imageurl = "IMAGEURL"
    }
    /** Name of the extra data field */
    public var key: String?
    /** Value of the extra data field */
    public var value: String?
    /** Type of the extra data field */
    public var type: ModelType?
    /** Add this field to the export of the product feed to the channel */
    public var isPublic: Bool?


    public enum CodingKeys: String, CodingKey { 
        case key = "Key"
        case value = "Value"
        case type = "Type"
        case isPublic = "IsPublic"
    }


}

