//
// MerchantCancellationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MerchantCancellationRequest: Codable {

    public enum ReasonCode: String, Codable { 
        case notInStock = "NOT_IN_STOCK"
        case damaged = "DAMAGED"
        case incomplete = "INCOMPLETE"
        case clientCancelled = "CLIENT_CANCELLED"
        case invalidAddress = "INVALID_ADDRESS"
        case other = "OTHER"
    }
    /** The unique cancellation reference used by the Merchant (sku) */
    public var merchantCancellationNo: String
    /** The unique order reference used by the Merchant (sku) */
    public var merchantOrderNo: String
    public var lines: [MerchantCancellationLineRequest]
    /** Reason for cancellation (text) */
    public var reason: String?
    /** Reason code for cancellation */
    public var reasonCode: ReasonCode?


    public enum CodingKeys: String, CodingKey { 
        case merchantCancellationNo = "MerchantCancellationNo"
        case merchantOrderNo = "MerchantOrderNo"
        case lines = "Lines"
        case reason = "Reason"
        case reasonCode = "ReasonCode"
    }


}

