//
// MerchantSingleOrderReturnLineResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MerchantSingleOrderReturnLineResponse: Codable {

    /** The unique product reference used by the Merchant (sku) */
    public var merchantProductNo: String?
    /** The accepted quantity of returned products in this orderline */
    public var acceptedQuantity: Int?
    /** The rejected quantity of returned products in this orderline */
    public var rejectedQuantity: Int?
    /** Number of items of the product in this return */
    public var quantity: Int

    public init(merchantProductNo: String?, acceptedQuantity: Int?, rejectedQuantity: Int?, quantity: Int) {
        self.merchantProductNo = merchantProductNo
        self.acceptedQuantity = acceptedQuantity
        self.rejectedQuantity = rejectedQuantity
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey { 
        case merchantProductNo = "MerchantProductNo"
        case acceptedQuantity = "AcceptedQuantity"
        case rejectedQuantity = "RejectedQuantity"
        case quantity = "Quantity"
    }


}

