//
// MerchantOfferGetStockResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MerchantOfferGetStockResponse: Codable {

    /** The product SKU */
    public var merchantProductNo: String?
    /** The ChannelEngine id of the stock location */
    public var stockLocationId: Int?
    /** The quantity of products in stock at the stock location */
    public var stock: Int?


    public enum CodingKeys: String, CodingKey { 
        case merchantProductNo = "MerchantProductNo"
        case stockLocationId = "StockLocationId"
        case stock = "Stock"
    }


}

