//
// MerchantOrderLineExtraDataResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MerchantOrderLineExtraDataResponse: Codable {

    public var key: String?
    public var value: String?

    public init(key: String?, value: String?) {
        self.key = key
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case key = "Key"
        case value = "Value"
    }


}

