//
// MerchantReturnLineUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MerchantReturnLineUpdateRequest: Codable {

    /** The unique product reference used by the Merchant (sku) */
    public var merchantProductNo: String
    /** The amount of items that have been accepted */
    public var acceptedQuantity: Int
    /** The amount of items that have been rejected */
    public var rejectedQuantity: Int

    public init(merchantProductNo: String, acceptedQuantity: Int, rejectedQuantity: Int) {
        self.merchantProductNo = merchantProductNo
        self.acceptedQuantity = acceptedQuantity
        self.rejectedQuantity = rejectedQuantity
    }

    public enum CodingKeys: String, CodingKey { 
        case merchantProductNo = "MerchantProductNo"
        case acceptedQuantity = "AcceptedQuantity"
        case rejectedQuantity = "RejectedQuantity"
    }


}

