//
// MerchantOrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MerchantOrderResponse: Codable {

    public enum ChannelOrderSupport: String, Codable { 
        case _none = "NONE"
        case orders = "ORDERS"
        case splitOrders = "SPLIT_ORDERS"
        case splitOrderLines = "SPLIT_ORDER_LINES"
    }
    public enum Status: String, Codable { 
        case inProgress = "IN_PROGRESS"
        case shipped = "SHIPPED"
        case inBackorder = "IN_BACKORDER"
        case canceled = "CANCELED"
        case manco = "MANCO"
        case inCombi = "IN_COMBI"
        case closed = "CLOSED"
        case new = "NEW"
        case returned = "RETURNED"
        case requiresCorrection = "REQUIRES_CORRECTION"
    }
    /** The unique identifier used by ChannelEngine. This identifier does  not have to be saved. It should only be used in a call to acknowledge the order. */
    public var _id: Int?
    public var channelName: String?
    public var channelOrderSupport: ChannelOrderSupport?
    public var channelOrderNo: String?
    public var status: Status?
    /** The total value of the order lines including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var subTotalInclVat: Double?
    /** The total amount of VAT charged over the order lines  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var subTotalVat: Double?
    /** The total amount of VAT charged over the shipping fee  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var shippingCostsVat: Double?
    /** The total value of the order including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var totalInclVat: Double?
    /** The total amount of VAT charged over the total value of te order  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var totalVat: Double?
    /** The total value of the order lines including VAT  (in the currency in which the order was paid for). */
    public var originalSubTotalInclVat: Double?
    /** The total amount of VAT charged over the order lines  (in the currency in which the order was paid for). */
    public var originalSubTotalVat: Double?
    /** The shipping fee including VAT  (in the currency in which the order was paid for). */
    public var originalShippingCostsInclVat: Double?
    /** The total amount of VAT charged over the shipping fee  (in the currency in which the order was paid for). */
    public var originalShippingCostsVat: Double?
    /** The total value of the order including VAT  (in the currency in which the order was paid for). */
    public var originalTotalInclVat: Double?
    /** The total amount of VAT charged over the total value of te order  (in the currency in which the order was paid for). */
    public var originalTotalVat: Double?
    public var lines: [MerchantOrderLineResponse]?
    public var phone: String?
    public var email: String
    public var companyRegistrationNo: String?
    public var vatNo: String?
    public var paymentMethod: String
    /** The shipping fee including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var shippingCostsInclVat: Double
    public var currencyCode: String
    public var orderDate: Date
    public var channelCustomerNo: String?
    public var billingAddress: Address
    public var shippingAddress: Address
    public var extraData: [String:String]?


    public enum CodingKeys: String, CodingKey { 
        case _id = "Id"
        case channelName = "ChannelName"
        case channelOrderSupport = "ChannelOrderSupport"
        case channelOrderNo = "ChannelOrderNo"
        case status = "Status"
        case subTotalInclVat = "SubTotalInclVat"
        case subTotalVat = "SubTotalVat"
        case shippingCostsVat = "ShippingCostsVat"
        case totalInclVat = "TotalInclVat"
        case totalVat = "TotalVat"
        case originalSubTotalInclVat = "OriginalSubTotalInclVat"
        case originalSubTotalVat = "OriginalSubTotalVat"
        case originalShippingCostsInclVat = "OriginalShippingCostsInclVat"
        case originalShippingCostsVat = "OriginalShippingCostsVat"
        case originalTotalInclVat = "OriginalTotalInclVat"
        case originalTotalVat = "OriginalTotalVat"
        case lines = "Lines"
        case phone = "Phone"
        case email = "Email"
        case companyRegistrationNo = "CompanyRegistrationNo"
        case vatNo = "VatNo"
        case paymentMethod = "PaymentMethod"
        case shippingCostsInclVat = "ShippingCostsInclVat"
        case currencyCode = "CurrencyCode"
        case orderDate = "OrderDate"
        case channelCustomerNo = "ChannelCustomerNo"
        case billingAddress = "BillingAddress"
        case shippingAddress = "ShippingAddress"
        case extraData = "ExtraData"
    }


}

