//
// MerchantCancellationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MerchantCancellationRequest: Codable {

    public enum ReasonCode: String, Codable { 
        case notInStock = "NOT_IN_STOCK"
        case damaged = "DAMAGED"
        case incomplete = "INCOMPLETE"
        case clientCancelled = "CLIENT_CANCELLED"
        case invalidAddress = "INVALID_ADDRESS"
        case other = "OTHER"
    }
    public var merchantCancellationNo: String
    public var merchantOrderNo: String
    public var lines: [MerchantCancellationLineRequest]
    public var reason: String?
    public var reasonCode: ReasonCode?


    public enum CodingKeys: String, CodingKey { 
        case merchantCancellationNo = "MerchantCancellationNo"
        case merchantOrderNo = "MerchantOrderNo"
        case lines = "Lines"
        case reason = "Reason"
        case reasonCode = "ReasonCode"
    }


}

