//
// MerchantOrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MerchantOrderResponse: Codable {

    public enum ChannelOrderSupport: String, Codable { 
        case _none = "NONE"
        case orders = "ORDERS"
        case splitOrders = "SPLIT_ORDERS"
        case splitOrderLines = "SPLIT_ORDER_LINES"
    }
    public enum Status: String, Codable { 
        case inProgress = "IN_PROGRESS"
        case shipped = "SHIPPED"
        case inBackorder = "IN_BACKORDER"
        case manco = "MANCO"
        case inCombi = "IN_COMBI"
        case closed = "CLOSED"
        case new = "NEW"
        case returned = "RETURNED"
        case requiresCorrection = "REQUIRES_CORRECTION"
    }
    /** The unique identifier used by ChannelEngine. This identifier does  not have to be saved. It should only be used in a call to acknowledge the order. */
    public var _id: Int?
    /** The name of the channel */
    public var channelName: String?
    /** The type of orders the channel support. */
    public var channelOrderSupport: ChannelOrderSupport?
    /** The unique order reference used by the channel */
    public var channelOrderNo: String?
    /** The status of the order */
    public var status: Status?
    /** Indicating whether the order is a business order */
    public var isBusinessOrder: Bool?
    /** The billing or invoice address */
    public var billingAddress: MerchantAddressResponse?
    /** The shipping address */
    public var shippingAddress: MerchantAddressResponse?
    /** The total value of the order lines including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var subTotalInclVat: Double?
    /** The total amount of VAT charged over the order lines  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var subTotalVat: Double?
    /** The total amount of VAT charged over the shipping fee  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var shippingCostsVat: Double?
    /** The total value of the order including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var totalInclVat: Double?
    /** The total amount of VAT charged over the total value of te order  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var totalVat: Double?
    /** The total value of the order lines including VAT  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalSubTotalInclVat: Double?
    /** The total amount of VAT charged over the order lines  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalSubTotalVat: Double?
    /** The shipping fee including VAT  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalShippingCostsInclVat: Double?
    /** The total amount of VAT charged over the shipping fee  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalShippingCostsVat: Double?
    /** The total value of the order including VAT  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalTotalInclVat: Double?
    /** The total amount of VAT charged over the total value of te order  (in the currency in which the order was paid for, see CurrencyCode). */
    public var originalTotalVat: Double?
    public var lines: [MerchantOrderLineResponse]?
    /** The customer&#39;s telephone number */
    public var phone: String?
    /** The customer&#39;s email */
    public var email: String
    /** Optional. A company&#39;s chamber of commerce number */
    public var companyRegistrationNo: String?
    /** Optional. A company&#39;s VAT number */
    public var vatNo: String?
    /** The payment method used on the order */
    public var paymentMethod: String?
    /** The shipping fee including VAT  (in the shop&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var shippingCostsInclVat: Double
    /** The currency code for the amounts of the order */
    public var currencyCode: String
    /** The date the order was done */
    public var orderDate: Date
    /** The unique customer reference used by the channel */
    public var channelCustomerNo: String?
    /** Extra data on the order */
    public var extraData: [String:String]?

    public init(_id: Int?, channelName: String?, channelOrderSupport: ChannelOrderSupport?, channelOrderNo: String?, status: Status?, isBusinessOrder: Bool?, billingAddress: MerchantAddressResponse?, shippingAddress: MerchantAddressResponse?, subTotalInclVat: Double?, subTotalVat: Double?, shippingCostsVat: Double?, totalInclVat: Double?, totalVat: Double?, originalSubTotalInclVat: Double?, originalSubTotalVat: Double?, originalShippingCostsInclVat: Double?, originalShippingCostsVat: Double?, originalTotalInclVat: Double?, originalTotalVat: Double?, lines: [MerchantOrderLineResponse]?, phone: String?, email: String, companyRegistrationNo: String?, vatNo: String?, paymentMethod: String?, shippingCostsInclVat: Double, currencyCode: String, orderDate: Date, channelCustomerNo: String?, extraData: [String:String]?) {
        self._id = _id
        self.channelName = channelName
        self.channelOrderSupport = channelOrderSupport
        self.channelOrderNo = channelOrderNo
        self.status = status
        self.isBusinessOrder = isBusinessOrder
        self.billingAddress = billingAddress
        self.shippingAddress = shippingAddress
        self.subTotalInclVat = subTotalInclVat
        self.subTotalVat = subTotalVat
        self.shippingCostsVat = shippingCostsVat
        self.totalInclVat = totalInclVat
        self.totalVat = totalVat
        self.originalSubTotalInclVat = originalSubTotalInclVat
        self.originalSubTotalVat = originalSubTotalVat
        self.originalShippingCostsInclVat = originalShippingCostsInclVat
        self.originalShippingCostsVat = originalShippingCostsVat
        self.originalTotalInclVat = originalTotalInclVat
        self.originalTotalVat = originalTotalVat
        self.lines = lines
        self.phone = phone
        self.email = email
        self.companyRegistrationNo = companyRegistrationNo
        self.vatNo = vatNo
        self.paymentMethod = paymentMethod
        self.shippingCostsInclVat = shippingCostsInclVat
        self.currencyCode = currencyCode
        self.orderDate = orderDate
        self.channelCustomerNo = channelCustomerNo
        self.extraData = extraData
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "Id"
        case channelName = "ChannelName"
        case channelOrderSupport = "ChannelOrderSupport"
        case channelOrderNo = "ChannelOrderNo"
        case status = "Status"
        case isBusinessOrder = "IsBusinessOrder"
        case billingAddress = "BillingAddress"
        case shippingAddress = "ShippingAddress"
        case subTotalInclVat = "SubTotalInclVat"
        case subTotalVat = "SubTotalVat"
        case shippingCostsVat = "ShippingCostsVat"
        case totalInclVat = "TotalInclVat"
        case totalVat = "TotalVat"
        case originalSubTotalInclVat = "OriginalSubTotalInclVat"
        case originalSubTotalVat = "OriginalSubTotalVat"
        case originalShippingCostsInclVat = "OriginalShippingCostsInclVat"
        case originalShippingCostsVat = "OriginalShippingCostsVat"
        case originalTotalInclVat = "OriginalTotalInclVat"
        case originalTotalVat = "OriginalTotalVat"
        case lines = "Lines"
        case phone = "Phone"
        case email = "Email"
        case companyRegistrationNo = "CompanyRegistrationNo"
        case vatNo = "VatNo"
        case paymentMethod = "PaymentMethod"
        case shippingCostsInclVat = "ShippingCostsInclVat"
        case currencyCode = "CurrencyCode"
        case orderDate = "OrderDate"
        case channelCustomerNo = "ChannelCustomerNo"
        case extraData = "ExtraData"
    }


}

