//
// ProductMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProductMessage: Codable {

    public var name: String?
    public var reference: String?
    public var warnings: [String]?
    public var errors: [String]?

    public init(name: String?, reference: String?, warnings: [String]?, errors: [String]?) {
        self.name = name
        self.reference = reference
        self.warnings = warnings
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case reference = "Reference"
        case warnings = "Warnings"
        case errors = "Errors"
    }


}

