//
// ChannelProcessedChangesRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ChannelProcessedChangesRequest: Codable {

    /** A collection of pairs of merchant and channel references  of the products which are successfully created. The channel references  are saved such that in subsequent calls these can be used instead of the   merchant references. */
    public var created: [ChannelReferencesRequest]?
    /** The channel references of the products which are successfully updated. */
    public var updated: [String]?
    /** The channel references of the products which are successfully removed. */
    public var removed: [String]?


    
    public init(created: [ChannelReferencesRequest]?, updated: [String]?, removed: [String]?) {
        self.created = created
        self.updated = updated
        self.removed = removed
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(created, forKey: "Created")
        try container.encodeIfPresent(updated, forKey: "Updated")
        try container.encodeIfPresent(removed, forKey: "Removed")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        created = try container.decodeIfPresent([ChannelReferencesRequest].self, forKey: "Created")
        updated = try container.decodeIfPresent([String].self, forKey: "Updated")
        removed = try container.decodeIfPresent([String].self, forKey: "Removed")
    }
}

