//
// EntitiesAddressModels.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EntitiesAddressModels: Codable {

    public enum Gender: String, Codable { 
        case male = "MALE"
        case female = "FEMALE"
        case notApplicable = "NOT_APPLICABLE"
    }
    public var gender: Gender?
    public var companyName: String?
    public var firstName: String?
    public var lastName: String?
    public var streetName: String?
    public var houseNr: String?
    public var houseNrAddition: String?
    public var zipCode: String?
    public var city: String?
    public var region: String?
    public var countryIso: String?
    public var original: String?


    public enum CodingKeys: String, CodingKey { 
        case gender = "Gender"
        case companyName = "CompanyName"
        case firstName = "FirstName"
        case lastName = "LastName"
        case streetName = "StreetName"
        case houseNr = "HouseNr"
        case houseNrAddition = "HouseNrAddition"
        case zipCode = "ZipCode"
        case city = "City"
        case region = "Region"
        case countryIso = "CountryIso"
        case original = "Original"
    }


}

