//
// MerchantOrderResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MerchantOrderResponse: Codable {

    public enum ChannelOrderSupport: String, Codable { 
        case _none = "NONE"
        case orders = "ORDERS"
        case splitOrders = "SPLIT_ORDERS"
        case splitOrderLines = "SPLIT_ORDER_LINES"
    }
    public enum Status: String, Codable { 
        case inProgress = "IN_PROGRESS"
        case shipped = "SHIPPED"
        case inBackorder = "IN_BACKORDER"
        case canceled = "CANCELED"
        case manco = "MANCO"
        case inCombi = "IN_COMBI"
        case closed = "CLOSED"
        case new = "NEW"
        case returned = "RETURNED"
        case requiresCorrection = "REQUIRES_CORRECTION"
    }
    /** The unique identifier used by ChannelEngine. This identifier does  not have to be saved. It should only be used in a call to acknowledge the order. */
    public var _id: Int?
    public var channelName: String?
    public var channelOrderSupport: ChannelOrderSupport?
    public var channelOrderNo: String?
    public var status: Status?
    public var lines: [MerchantOrderLineResponse]?
    public var phone: String?
    public var email: String
    public var companyRegistrationNo: String?
    public var vatNo: String?
    public var paymentMethod: String
    /** The shipping fee including VAT  (in the tenant&#39;s base currency calculated using the exchange rate at the time of ordering). */
    public var shippingCostsInclVat: Double
    public var currencyCode: String
    public var orderDate: Date
    public var channelCustomerNo: String?
    public var billingAddress: EntitiesAddressModels
    public var shippingAddress: EntitiesAddressModels
    public var extraData: [String:String]?


    public enum CodingKeys: String, CodingKey { 
        case _id = "Id"
        case channelName = "ChannelName"
        case channelOrderSupport = "ChannelOrderSupport"
        case channelOrderNo = "ChannelOrderNo"
        case status = "Status"
        case lines = "Lines"
        case phone = "Phone"
        case email = "Email"
        case companyRegistrationNo = "CompanyRegistrationNo"
        case vatNo = "VatNo"
        case paymentMethod = "PaymentMethod"
        case shippingCostsInclVat = "ShippingCostsInclVat"
        case currencyCode = "CurrencyCode"
        case orderDate = "OrderDate"
        case channelCustomerNo = "ChannelCustomerNo"
        case billingAddress = "BillingAddress"
        case shippingAddress = "ShippingAddress"
        case extraData = "ExtraData"
    }


}

